<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
$catArray = array("13","58","59","60");
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$subcategory = $objectManager->create('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categoryCollection = $subcategory->create();
 $categoryCollection->addFieldToFilter('entity_id', ['in' => $catArray ]);
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    
    <?php
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    $currentCategoryName = $category->getName();
    if(in_array($category->getId(), $catArray) ){
        
        ?>
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Filter By Category')) ?></label>

    <select onchange="window.location.href = this.value" name="category" id="category" class="sorter-options">
    <?php
    
    foreach($categoryCollection->getItems() as  $cat){

        $category = $objectManager->create('Magento\Catalog\Model\Category')->load($cat->getId());
         
        $name = $category->getName();
        $url = $cat->getUrl();
        if ($category->getId() == 13){
            ?>
            <option value="<?=$url?>" <?php if($currentCategoryName == $name) {echo "selected";} ?>><?='Show All'?></option>
            <?php
        } else {
        ?>
        <option value="<?=$url?>" <?php if($currentCategoryName == $name) {echo "selected";} ?>><?=$name?></option>
        <?php
        }
     }

       ?>
    </select>
    <?php
}
?>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
