<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item); ?>
<tr>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?= $block->getColumnHtml($_item, 'price'); ?>
    </td>
    <td class="col-ordered-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
    <?php if ($block->canParentReturnToStock($_item)) : ?>
        <td class="col-return-to-stock">
            <?php if ($block->canReturnItemToStock($_item)) : ?>
                <input type="checkbox"
                       class="admin__control-checkbox"
                       name="creditmemo[items][<?= $block->escapeHtml($_item->getOrderItemId()) ?>][back_to_stock]"
                       value="1"
                       <?= $block->escapeHtml($_item->getBackToStock() || $_item->getOrderItem()->getProductType() == 'rental' ? 'checked' : '') ?>
                       <?= $block->escapeHtml($_item->getOrderItem()->getProductType() == 'rental' ? 'disabled' : '') ?>
                />
                <label class="admin__field-label"></label>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="col-refund col-qty">
        <?php if ($block->canEditQty()) : ?>
            <input type="text"
                   class="input-text admin__control-text qty-input"
                   name="creditmemo[items][<?= $block->escapeHtml($_item->getOrderItemId()) ?>][qty]"
                   value="<?= $block->escapeHtml($_item->getQty() * 1) ?>"/>
        <?php else : ?>
            <?= $block->escapeHtml($_item->getQty() * 1) ?>
        <?php endif; ?>
    </td>
    <td class="col-subtotal">
        <?= $block->getColumnHtml($_item, 'subtotal'); ?>
    </td>
    <td class="col-tax-amount"><?= $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discont"><?= $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?= $block->getColumnHtml($_item, 'total'); ?>
    </td>
</tr>
