<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$resultPageFactory = $objectManager->get('Magento\Framework\View\Result\PageFactory');
$resultPage = $resultPageFactory->create();
//$block=  $resultPage->getLayout()->createBlock('AscentDigital\Reports\Block\Reports\FirstNet\InventoryGraphs');
$count = count($block->getProducts());
// foreach($block->getProducts() as $orders){
//     echo"<pre>";
//     print_r($orders->getTotalOrders());
// }
// die("error");
// echo "<pre>";print_r($count);die("error");
if ($count > 0) {
    ?>
<div>
    <h1>Order Inventory Orders Chart By Sku Chart</h1>
</div>

    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            
            /////////////////////////////// order status report Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("inventory-orders-by-sku", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                <?php
                foreach ($block->getProducts() as $order) {
                    ?>
                chart.data.push({
                    x_axes: "<?php echo $order['sku']; ?>",
                    value: <?= $order->getTotalOrders(); ?>
                });
                          
                
                <?php
                }
                ?>
                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()

            
        });
    </script>
    <style>
        #inventory-orders-by-sku {
            width: 100%;
            height: 500px;
        }
    </style>
    
    <div id="inventory-orders-by-sku"></div>
    <hr>
<div>
    <h1>Order Inventory Ordered Qty Chart By Sku</h1>
</div>

    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            
            /////////////////////////////// order status report Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("inventory-orderd-qty-by-sku", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                <?php
                foreach ($block->getProducts() as $order) {
                    ?>
                chart.data.push({
                    x_axes: "<?php echo $order['sku']; ?>",
                    value: <?=  $order->getTotalQty(); ?>
                });
                <?php
                }
                ?>
                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()

            
        });
    </script>
    <style>
        #inventory-orderd-qty-by-sku {
            width: 100%;
            height: 500px;
        }
    </style>
    <div id="inventory-orderd-qty-by-sku"></div>
    <hr>
<div>
    <h1>Order Inventory On Demo Orders Chart By Sku</h1>
</div>

    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            
            /////////////////////////////// order status report Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("inventory-orderd-on-demo", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                <?php
                foreach ($block->getProducts() as $order) {
                    ?>
                          
                chart.data.push({
                    x_axes: "<?php echo $order['sku']; ?>",
                    value: <?= $block->getOnDemo($order['sku']); ?>
                });
                <?php
                }
                ?>
                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()

            
        });
    </script>
    <style>
        #inventory-orderd-on-demo {
            width: 100%;
            height: 500px;
        }
    </style>
    
    <div id="inventory-orderd-on-demo"></div>
    <hr>
<div>
    <h1>Order Inventory Due Orders Chart By Sku</h1>
</div>

    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            
            /////////////////////////////// order status report Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("inventory-due-order", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                <?php
                foreach ($block->getProducts() as $order) {
                    ?>
                chart.data.push({
                    x_axes: "<?php echo $order['sku']; ?>",
                     value: <?= $block->getDue($order['sku']); ?>
                });
            
                <?php
                }
                ?>
                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()

            
        });
    </script>
    <style>
        #inventory-due-order {
            width: 100%;
            height: 500px;
        }
    </style>
    <div id="inventory-due-order"></div>
    <hr>
<div>
    <h1>Order Inventory Returned Orders Chart By Sku</h1>
</div>

    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            
            /////////////////////////////// order status report Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("inventory-returned-order", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                <?php
                foreach ($block->getProducts() as $order) {
                    ?>
                
                chart.data.push({
                    x_axes: "<?php echo $order['sku']; ?>",
                     value: <?= $block->getReturned($order['sku']); ?>
                });
                <?php
                }
                ?>
                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()

            
        });
    </script>
    <style>
        #inventory-returned-order {
            width: 100%;
            height: 500px;
        }
    </style>
    <div id="inventory-returned-order"></div>
    <hr>
<?php }?>