<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$resultPageFactory = $objectManager->get('Magento\Framework\View\Result\PageFactory');
$resultPage = $resultPageFactory->create();
$block=  $resultPage->getLayout()->createBlock('AscentDigital\Reports\Block\Reports\FirstNet\OrderStatusReportGraph');
// $status = $block->orderStatus;
// $orders = $block->getOrders($this->$orderStatus);
// echo "<pre>";
// print_r($orders);
// die();
if ($block->getOrders('Shipping') > 0 || $block->getOrders('Processing') > 0 || $block->getOrders('Complete') > 0) {
    ?>
<div>
    <h1>Order Status Report Graph</h1>
</div>

    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            
            /////////////////////////////// order status report Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("order-status-report-chart", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                chart.data = [
                          {
                          x_axes: "Shipping",
                          value: <?= $block->getOrders('Shipping') ?>
                          },
                          {
                          x_axes: "Processing",
                          value: <?= $block->getOrders('Processing') ?>
                          },
                          {
                          x_axes: "Complete",
                          value: <?= $block->getOrders('Complete') ?>
                          }
                          
                          ];

                // Create axes
                // var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                // categoryAxis.dataFields.category = "x_axes";
                // categoryAxis.renderer.grid.template.location = 0;
                // categoryAxis.renderer.minGridDistance = 30;
                // categoryAxis.renderer.labels.template.horizontalCenter = "right";
                // categoryAxis.renderer.labels.template.verticalCenter = "middle";
                // categoryAxis.renderer.labels.template.rotation = 270;
                // categoryAxis.tooltip.disabled = true;
                // categoryAxis.renderer.minHeight = 110;

                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()

            
        });
    </script>
    <style>
        #order-status-report-chart {
            width: 100%;
            height: 500px;
        }
    </style>
    <div id="order-status-report-chart"></div>
    <hr>
<?php }?>