<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$resultPageFactory = $objectManager->get('Magento\Framework\View\Result\PageFactory');
$resultPage = $resultPageFactory->create();
$block = $resultPage->getLayout()->createBlock('AscentDigital\Reports\Block\Reports\FirstNet\StatusWiseOrderQuantityGraph');

if ($block->getQuantity('Shipping') > 0 || $block->getQuantity('Processing') > 0 || $block->getQuantity('Complete') > 0) {
    ?>

    <div>
        <h1>Status Wise Order Quanticcty Graph</h1>
    </div>

    <script>
        requirejs(['jquery', 'amcharts'], function ($, amcharts) {

            /////////////////////////////// order status report Chart
            am4core.ready(function () {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("status-wise-order-quantity-chart", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                chart.data = [
                           <?php if ($block -> getQuantity('Shipping') >= 0) {?>
                    {
                        x_axes: "Shipping",
                            value: <?= $block->getQuantity('Shipping') ?>
                    },
               <?php }?>
               <?php if ($block -> getQuantity('Processing') >= 0) {?>
                    {
                        x_axes: "Processing",
                            value: <?= $block->getQuantity('Processing') ?>
                    },
                <?php }?>
                <?php if ($block -> getQuantity('Complete') >= 0) {?>
                    {
                        x_axes: "Complete",
                            value: <?= $block->getQuantity('Complete') ?>
                    }
              <?php  }?>
                          
                              ];

                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";


                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function (fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()


        });
    </script>
    <style>
        #status-wise-order-quantity-chart {
            width: 100%;
            height: 500px;
        }
    </style>
    <div id="status-wise-order-quantity-chart"></div>
    <hr>
<?php } ?>