
<?php
$_orders = $block->getOrders();
    if ($_orders && count($_orders)) {
        // foreach ($_orders as $_order) {
        //     echo $block->getOrderCount($_order->getCustomerEmail()) . "<br>";
        //     echo $_order->getGrandTotal() . "<br>";
        //     echo $_order->getTotalQtyOrdered() . "<br>";
        // }
        ?>
<div>
    <h1>Report Graph</h1>
</div>
    <script>
        requirejs(['jquery', 'amcharts'], function($, amcharts) {
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("salesorder-report-totalnumber-chart", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                chart.data = [];
                <?php
                foreach ($_orders as $_order) {
                    ?>
                    chart.data.push({
                        x_axes: "<?= $_order->getCustomerEmail() ?>",
                        value: <?= $block->getOrderCount($_order->getCustomerEmail()) ?>
                    });
                <?php
                }
                ?>

                // Create axes
                // var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                // categoryAxis.dataFields.category = "x_axes";
                // categoryAxis.renderer.grid.template.location = 0;
                // categoryAxis.renderer.minGridDistance = 30;
                // categoryAxis.renderer.labels.template.horizontalCenter = "right";
                // categoryAxis.renderer.labels.template.verticalCenter = "middle";
                // categoryAxis.renderer.labels.template.rotation = 270;
                // categoryAxis.tooltip.disabled = true;
                // categoryAxis.renderer.minHeight = 110;

                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";

                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()
            /////////////////////////////// Total Qty Order Chart
            am4core.ready(function() {

                // Themes begin
                am4core.useTheme(am4themes_animated);
                // Themes end

                // Create chart instance
                var chart = am4core.create("salesorder-report-totalqtyordered-chart", am4charts.XYChart);
                chart.scrollbarX = new am4core.Scrollbar();

                // Add data
                chart.data = [];
                <?php
                foreach ($_orders as $_order) {
                    ?>
                    chart.data.push({
                        x_axes: "<?= $_order->getCustomerEmail() ?>",
                        value: <?= $_order->getTotalQtyOrdered() ?>
                    });
                <?php
                }
                ?>

                // Create axes
                // var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                // categoryAxis.dataFields.category = "x_axes";
                // categoryAxis.renderer.grid.template.location = 0;
                // categoryAxis.renderer.minGridDistance = 30;
                // categoryAxis.renderer.labels.template.horizontalCenter = "right";
                // categoryAxis.renderer.labels.template.verticalCenter = "middle";
                // categoryAxis.renderer.labels.template.rotation = 270;
                // categoryAxis.tooltip.disabled = true;
                // categoryAxis.renderer.minHeight = 110;

                // Create axes
                var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
                categoryAxis.renderer.grid.template.location = 0;
                categoryAxis.dataFields.category = "x_axes";
                categoryAxis.renderer.minGridDistance = 40;
                categoryAxis.fontSize = 11;
                var labelX = categoryAxis.renderer.labels.template;
                labelX.maxWidth = 200;
                labelX.dy = 5;
                labelX.tooltipText = "{x_axes}";

                var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
                valueAxis.renderer.minWidth = 50;

                // Create series
                var series = chart.series.push(new am4charts.ColumnSeries());
                series.sequencedInterpolation = true;
                series.dataFields.valueY = "value";
                series.dataFields.categoryX = "x_axes";
                series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
                series.columns.template.strokeWidth = 0;

                series.tooltip.pointerOrientation = "vertical";

                series.columns.template.column.cornerRadiusTopLeft = 10;
                series.columns.template.column.cornerRadiusTopRight = 10;
                series.columns.template.column.fillOpacity = 0.8;

                // on hover, make corner radiuses bigger
                var hoverState = series.columns.template.column.states.create("hover");
                hoverState.properties.cornerRadiusTopLeft = 0;
                hoverState.properties.cornerRadiusTopRight = 0;
                hoverState.properties.fillOpacity = 1;

                series.columns.template.adapter.add("fill", function(fill, target) {
                    return chart.colors.getIndex(target.dataItem.index);
                });

                // Cursor
                chart.cursor = new am4charts.XYCursor();

            }); // end am4core.ready()
        });
    </script>
    <style>
        #salesorder-report-totalnumber-chart {
            width: 100%;
            height: 500px;
        }

        #salesorder-report-grandtotaltotal-chart {
            width: 100%;
            height: 500px;
        }

        #salesorder-report-totalqtyordered-chart {
            width: 100%;
            height: 500px;
        }
    </style>
    <div>
        <h2>Total no of orders by sales rep Chart</h2>
    </div>
    <div id="salesorder-report-totalnumber-chart"></div>
    <hr>
    <div>
        <h2>Total Qty Ordered By Sales Rep Chart</h2>
    </div>
    <div id="salesorder-report-totalqtyordered-chart"></div>
<?php
    }
?>