<div class="dashboard-container row">
    <div class="dashboard-secondary col-m-4">
        <div class="dashboard-item">
            <!-- <hr> -->
            <div class="dashboard-item-title">Reports List</div>
            <!-- <hr> -->
            <div class="dashboard-item-content">
                <table class="admin__table-primary dashboard-data" id="custom-dashboard-report-section">
                    <tr>
                        <th>Report #</th>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Total Sales Rep Orders Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/grid/totalsalesrepordersreport') ?>">View</a></td>
                    </tr>
                    <!-- <tr>
                        <td>2</td>
                        <td>Sales Rep Orders Report</td>
                        <td><a href="<?= ''//$block->getUrl('amreportbuilder/report/view/report_id/27') ?>">View</a></td>
                    </tr> -->
                    <tr>
                        <td>2</td>
                        <td>Sales Rep Orders Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/salesreporders') ?>">View</a></td>
                    </tr>
                    <!-- <tr>
                        <td>3</td>
                        <td>Order By Item Filter</td>
                        <td><a href="<?= ''//$block->getUrl('amreportbuilder/report/view/report_id/32') ?>">View</a></td>
                    </tr> -->
                    <!-- <tr>
                        <td>4</td>
                        <td>Orders Checked Out For Demo</td>
                        <td><a href="<?= ''//$block->getUrl('amreportbuilder/report/view/report_id/15') ?>">View</a></td>
                    </tr> -->
                    <tr>
                        <td>4</td>
                        <td>Orders Checked Out For Demo</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/demoorders') ?>">View</a></td>
                    </tr>
                    <!-- <tr>
                        <td>5</td>
                        <td>Order report By Inventory</td>
                        <td><a href="<?= ''//$block->getUrl('adminreports/grid/orderreportbyinventory') ?>">View</a></td>
                    </tr> -->
                    <tr>
                        <td>5</td>
                        <td>Order report By Inventory</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/orderinventoryreport') ?>">View</a></td>
                    </tr>
                    <!-- <tr>
                        <td>6</td>
                        <td>Orders Due Back Report</td>
                        <td><a href="<?= ''//$block->getUrl('amreportbuilder/report/view/report_id/24') ?>">View</a></td>
                    </tr> -->
                    <tr>
                        <td>6</td>
                        <td>Orders Due Back Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/dueorders') ?>">View</a></td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>Inventory Listing</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/orderinventory') ?>">View</a></td>
                    </tr>
                    
                    <tr>
                        <td>8</td>
                        <td>Orders Details Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/orderdetailreport') ?>">View</a></td>
                    </tr>

                    <tr>
                        <td>9</td>
                        <td>A/E Report – YTD</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/aeytdreport') ?>">View</a></td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>Advance Exchange Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/advanceexchangereport') ?>">View</a></td>
                    </tr>
                    <!-- <tr>
                        <td>10</td>
                        <td>Repair Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/repairreport') ?>">View</a></td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>Order Type Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/ordertypereport') ?>">View</a></td>
                    </tr> -->
                    <tr>
                        <td>11</td>
                        <td>Inventory Report</td>
                        <td><a href="<?= $block->getUrl('adminreports/reports/inventoryreport') ?>">View</a></td>
                    </tr>
                    
                </table>
            </div>
        </div>
    </div>
</div>
