<?php if($block->getCustomerInfo()){?>
<!-- <h2>Customer Informtion</h2> -->
<p><?php echo $block->getCustomerInfo();?></p>
<?php }?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
// $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue("web/unsecure/base_url");
// $files = $this->getRequest()->getFiles();
$customerFiles = $block->getCustomerFiles();
// print_r($customerFiles->getData());die();
if($customerFiles->getData()){
// echo $ids;
// print_r($id->getData());die('mateeen');
$isFirstIteration = true;
?>
 <div class="page-section-title">
            <h2 class="title"><?= $block->escapeHtml(__('Customer Files')) ?></h2>
        </div>
 <table class="data table table-order-items history">
                        <?php foreach($customerFiles as $customerFile){?>
                        <tr>
                            
                            <th><a href="<?= $url?>media/mobility_customer/attachment/<?= $customerFile->getFileName() ?>" id="show_file" name="show_file" target="_blank"><?= $block->escapeHtml(__($customerFile->getFileName())) ?></a></th>
                        </tr>
                       <?php } ?> 
                    </table>
                    <?php }?>