<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span>
                            <?= $block->escapeHtml(__('Qty')) ?>
                        </span></label>

                    <div class="control">
                        <input type="number" name="qty" id="qty" min="1" value="1"
                            title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty"
                            data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">



                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerSession = $objectManager->get('Magento\Customer\Model\Session');
                $customerId = $customerSession->getCustomer()->getId();
                $customerData = $objectManager->create('Magento\Customer\Model\Customer')->load($customerId);


                $cusLoc = $customerData->getLocationId();
                if (!empty($cusLoc)) {
                    $strCus = preg_split("/\,/", $cusLoc);
                    $proLoc = $_product['location_id'];
                    if ($proLoc != null) {
                        $strPro = explode(",", $proLoc);
                    }
                }

                $catArray = array("13", "58", "59", "60");
                if (array_intersect($_product->getCategoryIds(), $catArray)) {
                    if (!empty($cusLoc)) {
                        if ($customerData->getLocationId() != '') {
                            if (count(array_intersect($strCus, $strPro)) >= 1) {

                                $connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
                                $quant = $connection->fetchCol("SELECT qty FROM items_details WHERE location_id IN (" . $cusLoc . ") AND item_id='" . $_product['entity_id'] . "'");


                                if (array_sum($quant) == 0) {
                                    ?>
                                    <h2>
                                        <p style="color: tomato">
                                            <?php echo "No stock, Please contact CSM."; ?>
                                        </p>
                                    </h2>
                                    <?php
                                } else {
                                    ?>
                                    <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart"
                                        id="product-addtocart-button" disabled>
                                        <span>
                                            <?= $block->escapeHtml($buttonTitle) ?>
                                        </span>
                                    </button>
                                    <?php
                                }

                                ?>

                                <?php
                            }
                        }
                    }
                } else {
                    ?>
                    <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart"
                        id="product-addtocart-button" disabled>
                        <span>
                            <?= $block->escapeHtml($buttonTitle) ?>
                        </span>
                    </button>
                    <?php
                }
                ?>


                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<!-- <script type="text/x-magento-init">
{
    "#product_addtocart_form": {
        "Magento_Catalog/product/view/validation": {
            "bindSubmit": true,
            "radioCheckboxClosest": ".nested"
        }
    }
}
</script> -->


<script type="text/x-magento-init">
   {
    "#product_addtocart_form": {
        "Magento_Catalog/product/view/validation": {
            "bindSubmit": true,
            "radioCheckboxClosest": ".nested"
        }
    }
   }
</script>