;(function($){$.fn.simpleFAQ=function(o){var n=$(this);o=(o)?o:{};if(!o.node&&n.length){o.node=n;}
o.node=$(o.node);o.node.each(function(){var sf=new $.jk.SimpleFAQ(o);});return n;};if(!$.jk){$.jk={};}
$.jk.SimpleFAQ=function(o){var t=this,n;o=(o)?o:{};$.extend(t,((o)?o:{}));t.node=$(((o.node)?o.node:null));if(t.node&&t.node.length===1){n=t.node;}else{t.node=null;return t;}
if($.isArray(t.data)){this.buildFaqsFromData();}
n.addClass(t.ns+'_list');t.faqNodes=n.children(t.nodeType).addClass(t.ns+'_item');t.setupBasicActions();t.faqNodes.find('.'+t.answerClass).hide();t.showDefaultItem();if(t.allowSearch){t.searchNode=$(t.searchNode);if(t.searchNode.length){if(t.score===null&&(typeof $.score=='function')){t.score=$.score;}
if(typeof t.score=='function'){t.addSearchUI();if(!t.showAllOnEmpty){t.hideSearchResults(t.faqNodes);}}else{t.allowSearch=false;t.searchNode=null;t.score=null;}}else{t.allowSearch=false;t.searchNode=null;}}
n.data(t.ns,t).trigger('init.'+t.ns,[t]);};$.extend($.jk.SimpleFAQ.prototype,{data:null,nodeType:'li',questionClass:'question',answerClass:'answer',tagClass:'tags',showOnlyOne:false,changeHash:true,slideSpeed:500,allowSearch:false,score:null,searchNode:null,minSearchScore:0.5,sortSearch:false,showAllOnEmpty:true,caseSensitive:false,keyTimeout:400,partialTagScore:0.1,exactTagScore:0.2,node:null,ns:'simpleFAQ'});$.extend($.jk.SimpleFAQ.prototype,{setupBasicActions:function(){var t=this;t.node.on('mouseover','.'+t.questionClass,function(){$(this).addClass(t.ns+'Hover');}).on('mouseout','.'+t.questionClass,function(){$(this).removeClass(t.ns+'Hover');}).on('click.'+t.ns,'.'+t.questionClass,function(e){var faq=$(this).parents('.'+t.ns+'_item');if(t.showOnlyOne){t.hideAll(faq);}
t.toggleFaq(faq);});},buildFaqsFromData:function(){var t=this,fc="";for(var i=0,l=t.data.length;i<l;++i){fc+="<"+t.nodeType+">"+"<p class='"+t.questionClass+"'>"+t.data[i].question+"</p>"+"<div class='"+t.answerClass+"'>"+t.data[i].answer+"</div>"+"<p class='"+t.tagClass+"'>"+(t.data[i].tags||"")+"</p>"+"</"+t.nodeType+">";}
t.node.append(fc);},toggleFaq:function(faq,cb){var t=this;faq=(faq||$(t.faqNodes.get(0)));var ans=faq.find('.'+t.answerClass);cb=(cb||function(){});ans.slideToggle(t.slideSpeed,function(){if(ans.is(':visible')){faq.addClass(t.ns+'Showing');t.node.trigger('show.'+t.ns,[faq[0]]);if(t.changeHash){var h=faq.attr('id');if(h&&h.length>0){document.location.hash=escape(h);}}}else{faq.removeClass(t.ns+'Showing');}
cb();});},hideAll:function(except,cb){var t=this,cnt=0,vis=null;except=(except||null);cb=(cb||function(){});vis=t.faqNodes.find('.'+t.answerClass+':visible');if(except){vis=vis.not(except.find('.'+t.answerClass));}
if(vis.length){vis.slideUp(t.slideSpeed,function(){var p=$(this).parents('.'+t.ns+'_item').removeClass(t.ns+'Showing');t.node.trigger('hide.'+t.ns,[p[0]]);cnt++;if(cnt>=vis.length){cb();}});}else{cb();}},showDefaultItem:function(){var t=this,ch=document.location.hash,fn=null;if(ch&&ch.length>0){fn=$(ch);if(fn.length&&fn.is('.'+t.ns+'_item')){t.toggleFaq(fn);}}},hideSearchResults:function(nodes){var t=this;nodes.hide().removeClass(t.ns+'Result '+t.ns+'Showing').find('.'+t.answerClass).hide();},addSearchUI:function(){var t=this;if(!t.searchNode||!t.searchNode.length){return;}
t.__sto=null;t.searchNode.addClass(t.ns+'Search').keyup(function(e){clearTimeout(t.__sto);t.__sto=null;t.__sto=setTimeout(function(){t.handleSearchKey(t.searchNode.val());},t.keyTimeout);});},handleSearchKey:function(v){var t=this,scores=[];t.node.trigger('searchStart.'+t.ns);if(v.length<1){t.hideSearchResults(t.faqNodes);if(t.showAllOnEmpty){t.faqNodes.show();}
t.node.trigger('searchEnd.'+t.ns,[scores]);return scores;}
scores=t.doScoring(v);if(t.sortSearch){scores.sort(function(a,b){return b[0]-a[0];});t.node.trigger('sort.'+t.ns,[scores]);}
var resFaqs=[];for(var i=0,l=scores.length;i<l;++i){scores[i][1].show().addClass(t.ns+'Result');resFaqs.push(scores[i][1][0]);if(t.sortSearch){t.node.append(scores[i][1]);}}
t.hideSearchResults(t.faqNodes.not(resFaqs));t.node.trigger('searchEnd.'+t.ns,[scores]);return scores;},doScoring:function(v){var t=this,res=[],w=[];if(!v||!v.length){return res;}
v=""+((t.caseSensitive)?v:v.toLowerCase());w=(""+v).split(' ');t.faqNodes.each(function(){var faq=$(this),faqText="",s=0;faqText=faq.find('.'+t.questionClass).text();faqText+=" "+faq.find('.'+t.answerClass).text();faqText=(t.caseSensitive)?faqText:faqText.toLowerCase();for(var i=0,l=w.length;i<l;++i){if(!w[i].length){continue;}
s+=t.score(faqText,w[i]);}
s+=t.scoreTags(faq.find('.'+t.tagClass).text(),w);if(s>t.minSearchScore){res.push([s,faq]);}});return res;},scoreTags:function(tags,w){var t=this,s=0,tag="",m=null;if(!tags.length){return s;}
if(!w||!w.splice||!w.length){return s;}
tags=((t.caseSensitive)?tags:tags.toLowerCase()).replace(/\s?(,|;)\s?/g,' ');for(var i=0,l=w.length;i<l;++i){if(!w[i].length){continue;}
m=tags.match(new RegExp("[^\\s]*("+w[i]+")[^\\s]*"));if(m){if(m[0].length==m[1].length){s+=t.exactTagScore;}else{s+=t.partialTagScore;}}}
return s;}});})(jQuery);