<!DOCTYPE html>
<html>

<head>
    <title>Customer Approval</title>
    <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('AscentDigital_OrderApproval::css/bootstrap.min.css') ?>">
    <!-- <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('AscentDigital_OrderApproval::css/style.css') ?>"> -->
    <!--  -->
    <!-- <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/style.css"> -->
</head>

<body>
    <?php
   
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseUrl = $storeManager->getStore(2)->getBaseUrl();
    $baseUrl = str_replace("/firstnet/", "/", $baseUrl);
    ?>
    <style>
        body {
            font-family: Arial;
        }

        .main-header {
            background-color: #000;
        }

        .main-banner {
            /* min-height: 100vh; */
            background: url(<?= $baseUrl ?>media/customerApproval/firstnet-banner.jpeg?>) no-repeat;
            background-size: cover;
            height: calc(100vh - 86px);
        }

        .main-banner .container {
            height: calc(100vh - 86px);
        }

        .banner-caption {
            padding: 40px;
            background-color: rgba(0, 0, 0, 0.4);
        }

        .banner-caption h1 {
            color: #00e1fa;
            font-size: 38px;
        }

        .banner-caption p {
            line-height: 1.42857143;
            color: #fff;
            font-size: 22px;
        }
    </style>
    <div class="main-page">
        <div class="main-header">
            <div class="container">
                <div class="row">
                    <div class="col-12 pt-3 pb-3">
                        <img src="<?= $baseUrl ?>media/customerApproval/first-net-logo.png" alt="Logo">
                    </div>
                </div>
            </div>
        </div>
        <div class="main-banner">
            <div class="container">
                <div class="row h-100">
                    <div class="col-md-4"></div>
                    <div class="col-md-4 align-self-center">
                        <div class="banner-caption">

                            <h1>Thankyou for your approval</h1>
                            <p>Your order is in process, thankyou for submitting.</p>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
