<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">
            <?php /* @escapeNotVerified */ echo __('Customer Specific Prices Item Cron Job') ?>
        </span>

    </div>
    <div class="admin__page-section-content">
        <div class="order-information textfied" id="customer-specific-prices-item-cron-message">
            <div class="box">
                <div class="customer-specific-prices-item-cron-box-content">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
    <div class="admin__page-section-item-content edit-checkoutfield-date" id="run-customer-specific-prices-item-cron-job-form">
        <button id="customer-specific-prices-item-cron-submit">Run Customer Specific Prices Item Cron Job</button>
    </div>
   
</section>
<script type="text/javascript">
    // customer specific prices and items cron job
    document.querySelector('#customer-specific-prices-item-cron-submit').addEventListener('click', function() {
        document.querySelector('#customer-specific-prices-item-cron-submit').innerHTML = 'Running...';
        document.querySelector('#customer-specific-prices-item-cron-submit').disabled = true;
        require([
            'jquery',
            'mage/validation',
            'mage/translate',
            'jquery/ui'
        ], function($) {
            var url = '<?=
                        /** @noEscape */
                        $block->getUrl("nsproduct/cron/customerspecificpricing") ?>';
            jQuery.ajax({
                url: url,
                data: {
                    orderCron: 'run'
                },
                type: "POST",
                async: false,
            }).done(function(response) {
                $(".customer-specific-prices-item-cron-box-content").html("<span style='color:#008000; font-weight:bold'>Customer Specific Prices Item cron job completed. </span>");
                $("#customer-specific-prices-item-cron-submit").text('Run Customer Specific Prices Item Cron Job');
                document.querySelector('#customer-specific-prices-item-cron-submit').disabled = false;
            });

            //});            
        });
    });
    
</script>