<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">
            <?php /* @escapeNotVerified */ echo __('Shipping Cron Job') ?>
        </span>

    </div>
    <div class="admin__page-section-content">
        <div class="shipping-information textfied" id="shipping-cron-message">
            <div class="box">
                <div class="shipping-cron-box-content">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
    <div class="admin__page-section-item-content edit-checkoutfield-date" id="edit-checkoutfield-info-form">
        <button id="shipping-cron-submit">Run Shipping Cron Job</button>
    </div>
   
</section>

<script type="text/javascript">
    //shipping cron job
    document.querySelector('#shipping-cron-submit').addEventListener('click', function() {
        document.querySelector('#shipping-cron-submit').innerHTML = 'Running...';
        document.querySelector('#shipping-cron-submit').disabled = true;
        require([
            'jquery',
            'mage/validation',
            'mage/translate',
            'jquery/ui'
        ], function($) {
            var url = '<?=
                        /** @noEscape */
                        $block->getUrl("nsproduct/cron/shipping") ?>';
            jQuery.ajax({
                url: url,
                data: {
                    shippingCron: 'run'
                },
                type: "POST",
                async: false,
            }).done(function(response) {
                $(".shipping-cron-box-content").html("<span style='color:#008000; font-weight:bold'>Shipping cron job completed. </span>");
                $("#shipping-cron-submit").text('Run Shipping Cron Job');
                document.querySelector('#shipping-cron-submit').disabled = false;
            });

            //});            
        });
    });
   
</script>