<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $block->getOrders();
$orderStatus = $block->getAllOrderStatus();
$admin_base_url = $objectManager->create('Magento\Backend\Helper\Data')->getHomePageUrl();
?>
<html lang="en">

<head>

    <style>
        @media (min-width: 500px) {
            .row:after {
                content: " ";
                display: table;
                clear: both;
            }

            .row {
                padding-top: 25px;
            }

            .column-half {
                float: left;
                width: 20%;
                padding: 0 5px;
                box-sizing: border-box;
            }

            .column-half-right {
                float: right;
                width: 20%;
                box-sizing: border-box;
            }
        }

        .result {
            position: absolute;
            z-index: 999;
            top: 100%;
            left: 0;
            background: #fff;
            width: 100%;
            box-sizing: border-box;
        }

        .search-box {
            position: relative !important;
            line-height: 28px;
        }

        @media (min-width: 1260px) {
            .magezon-builder .mgz-container {
                width: 1260px;
            }
        }
    </style>
    <style>
    @media (min-width: 500px) {

        /* ym */
        .dropdown-content {
            position: absolute;
            background-color: #f6f6f6;
            overflow: auto;
        }

        .dropdown-content a {
            color: black;
            padding: 10px 16px;
            text-decoration: none;
            display: block;
            width: 200px;
        }

        .dropdown-content a:hover {
            background-color: #ddd;
        }

        .show {
            display: block !important;
        }

        .dropdown-values {
            display: none;
        }

        /* ym */
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .optdel {
            display: none !important;
        }

        .row {
            padding-top: 25px;
        }

        .multiselect-dropdown span.maxselected {
            width: 100px;
        }

        .column_total {
            font-weight: bold;

        }

        .column-half {
            float: left;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }

        .button-import {
            white-space: nowrap;
            margin-left: 10px;
        }

        .input-box {
            white-space: nowrap;
            margin-left: 10px;
        }

        .button-pdf {
            white-space: nowrap;
            margin-left: 10px;
        }

        .btn-primary {
            white-space: nowrap;
            margin-left: 10px;
        }

        .search-box {
            position: relative !important;
            line-height: 28px;
        }

        .result {
            position: absolute;
            z-index: 999;
            top: 100%;
            left: 0;
            background: #fff;
            width: 100%;
            box-sizing: border-box;
        }
    }
</style>

</head>
<style>
    .order-details-items {
        margin-top: -1px;
        padding: 25px;
    }

    .order-details-items {
        border: 1px solid #cccccc;
        margin-bottom: 40px;
        padding: 10px;
    }

    .button-import {
        white-space: nowrap;
        margin-left: 10px;
    }

    .button-pdf {
        white-space: nowrap;
        margin-left: 10px;
    }
</style>
<form method="GET" action="">
    <?php
       $skusArray = array();
       $selectedSkus = '';
       if (isset($_GET['skus'])) {
           $selectedSkus = $_GET['skus'];
       }
       ?>
    <?php
    if (isset($_POST['search'])) {
    } else {
        $_orders = $block->getOrders();
        echo $block->getChildHtml('info');
        if ($_orders && count($_orders)) {
    ?>
            <div class="row">
                <div class="column-half" style="width:95%;padding:5px 0;display: flex;">
                   
                    <input type="date"  class="form-control" name="from" value="<?php if(isset($_GET['from']) && !empty($_GET['from'])){
                            echo $_GET['from'];
                        }else{
                            echo '';
                        }?>"/>
                    
                        <input type="date" class="form-control" name="to" value="<?php if(isset($_GET['to']) && !empty($_GET['to'])){
                            echo $_GET['to'];
                        }else{
                            echo '';
                        }?>"/>

                    <?php
                    $productsData = $block->getProductSkus($selectedSkus);
                    ?>
                    <div class="input-box" style="clear: both;">
                        <div class="modelno-repeat">
                            <div class="search-box">


                                <select name="field2" id="field2" multiple multiselect-search="true" multiselect-select-all="false" style="width:350px;height:30px" multiselect-max-items="1" onclick="addSku()" onchange="addOptions(Array.from(this.selectedOptions).map(x=>x.value??x.text))">
                                    <?php
                                    foreach ($productsData as $proData) {
                                    ?>
                                        <option value="<?= $proData['sku'] ?>" selected><?= $proData['name'] ?></option>
                                    <?php }
                                    ?>
                                </select>

                                <input type="hidden" name="skus" id="skus" value="<?= $selectedSkus ?>" />
                                <i class="fa fa-plus add_fields"></i>
                                <div class="result"></div>
                            </div>
                        </div>
                    </div>
                
                        <div class="input-box" style="clear: both;">
                            <div class="modelno-repeat">
                                <div class="search-box">

                                    <input type="text" name="email" style="height:32px" id="sales-rep-email" autocomplete="off" placeholder="Sales rep email..." title="" value="<?php if (isset($_GET['email']) && !empty($_GET['email'])) {
                                                                            echo $_GET['email'];
                                                                      } else {
                                                                         echo '';
                                                                      } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                    <div id="SRDropdown" class="dropdown-content" style="width: 200px;">
                                        <div id="dropdown-values-sr" class="dropdown-values">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    
                 
                    

                               </div>

                               <div class="row">
                               <div class="column-half" style="width:115%;padding:5px 0;display: flex;">
                               <div class="input-box" style="clear: both;">
                                   <div class="modelno-repeat">
                                       <div class="search-box">
                                           <input type="text" name="sm_email" style="width:300px;height:32px" id="sales-man-email" autocomplete="off" placeholder="Sales manager email..." title="" value="<?php
                                                                                                                                                                                                           if (isset($_GET['sm_email']) && !empty($_GET['sm_email'])) {
                                                                                                                                                                                                               echo $_GET['sm_email'];
                                                                                                                                                                                                           } else {
                                                                                                                                                                                                               echo '';
                                                                                                                                                                                                           } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                           <div id="SMDropdown" class="dropdown-content">
                                               <div id="dropdown-values-sm" class="dropdown-values">

                                               </div>
                                           </div>
                                       </div>
                                   </div>
                               </div>
                               <div class="input-box" style="clear: both;">
                                   <div class="modelno-repeat">
                                       <div class="search-box">
                                           <input type="text" name="tm_email" style="width:300px;height:32px" id="territory-man-email" autocomplete="off" placeholder="Territory manager email..." title="" value="<?php
                                                                                                                                                                                                                   if (isset($_GET['tm_email']) && !empty($_GET['tm_email'])) {
                                                                                                                                                                                                                       echo $_GET['tm_email'];
                                                                                                                                                                                                                   } else {
                                                                                                                                                                                                                       echo '';
                                                                                                                                                                                                                   } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                           <div id="TMDropdown" class="dropdown-content">
                                               <div id="dropdown-values-tm" class="dropdown-values">

                                               </div>
                                           </div>
                                       </div>
                                   </div>
                               </div>
                               <div class="input-box" style="clear: both;">
                                   <div class="modelno-repeat">
                                       <div class="search-box">
                                           <input type="text" name="em_email" style="width:300px;height:32px" id="executive-man-email" autocomplete="off" placeholder="Executive manager email..." title="" value="<?php
                                                                                                                                                                                                                   if (isset($_GET['em_email']) && !empty($_GET['em_email'])) {
                                                                                                                                                                                                                       echo $_GET['em_email'];
                                                                                                                                                                                                                   } else {
                                                                                                                                                                                                                       echo '';
                                                                                                                                                                                                                   } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                           <div id="EMDropdown" class="dropdown-content">
                                               <div id="dropdown-values-em" class="dropdown-values">

                                               </div>
                                           </div>
                                       </div>
                                   </div>
                               </div>
                
                    <button class="btn btn-primary" name="search" style="width:150px;height:32px" type="submit"><span class="glyphicon glyphicon-search"></span> Search</button>
                    <button id="export_data" name="export_data" style="width:150px;height:32px" class="button-import" type="submit"> Export Data</button>
                    
                </div>
            </div>
            </div>
            <div class="column main" style="padding-top: 50px;padding-right: 30px;padding-bottom: 50px;width:100%">

                <?php foreach ($order->getData() as $data) {
                    $order = $objectManager->create('Magento\Sales\Api\Data\OrderInterface')->load($data['entity_id']);
                    $orderItems = $objectManager->create('Magento\Sales\Api\OrderRepositoryInterface');
                    $orderProducts = $orderItems->get($data['entity_id']);
                ?>




                    <div class="page-title-wrapper">

                        <div>
                            <div style="text-align:left">
                                <strong><span style="display: block; margin-bottom:16px;">
                                        Increment Id # <?php echo $data['increment_id']; ?> </span></strong>
                            </div>
                            <div style="text-align:right">
                                <a href="https://caad034362.nxcli.net/admin/sales/order/view/order_id/<?php echo $data['entity_id']; ?>" class="action view">
                                    <span>View Order</span>
                                </a>
                            </div>
                        </div>
                        <div>
                            <span style="display: block; margin-bottom:16px;">
                                SO # <?php echo $data['ns_so_number']; ?> </span>
                        </div>
                        <div>
                            <span style="display: block; margin-bottom:16px;">
                                Customer Email: <?php echo $data['customer_email']; ?> </span>
                        </div>
                    </div>
                    </br>

                    <div class="admin__table-wrapper">
                        <table class="data-table admin__table-primary edit-order-table">
                            <thead>
                                <tr class="headings">
                                    <th class="col-product"><span>Product Name</span></th>
                                    <th class="col-status"><span>SKU</span></th>
                                </tr>
                            </thead>
                            <tbody class="even">
                                <?php
                                if (!empty($order->getAllItems())) {
                                    foreach ($order->getAllItems() as $item) {

                                ?>
                                        <tr id="order-item-row-436">
                                            <td class="col name" style="background-color:white" data-th="Product Name"><strong class="product name product-item-name"><?php echo $item->getName(); ?></strong></td>
                                            <td class="col sku" style="background-color:white" data-th="SKU"> <?php echo $item->getSku(); ?></td>
                                            
                                        </tr>
                                <?php
                                    }
                                } ?>

                            </tbody>
                            
                        </table>
                    </div>
                    <hr>

                <?php } ?>

            </div>
        <?php } else { ?>
            <div class="row">
                <div class="column-half" style="width:115%;padding:5px 0;display: flex;">
                       
                        <input type="date" class="form-control" name="from" value="<?php if(isset($_GET['from']) && !empty($_GET['from'])){
                                echo $_GET['from'];
                            }else{
                                echo '';
                            }?>"/>
                        
                            <input type="date" class="form-control" name="to" value="<?php if(isset($_GET['to']) && !empty($_GET['to'])){
                                echo $_GET['to'];
                            }else{
                                echo '';
                            }?>"/>
                        
                    
                            <div class="input-box" style="clear: both;">
                                <div class="modelno-repeat">
                                    <div class="search-box">

                                        <input type="text" name="email" style="height:32px" id="sales-rep-email" autocomplete="off" placeholder="Sales rep email..." title="" value="<?php if (isset($_GET['email']) && !empty($_GET['email'])) {
                                                                                echo $_GET['email'];
                                                                          } else {
                                                                             echo '';
                                                                          } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                        <div id="SRDropdown" class="dropdown-content" style="width: 200px;">
                                            <div id="dropdown-values-sr" class="dropdown-values">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        
                        
                        <?php
                        $productsData = $block->getProductSkus($selectedSkus);
                        ?>
                        <div class="input-box" style="clear: both;">
                            <div class="modelno-repeat">
                                <div class="search-box">


                                    <select name="field2" id="field2" multiple multiselect-search="true" multiselect-select-all="false" style="width:200px;height:30px" multiselect-max-items="1" onclick="addSku()" onchange="addOptions(Array.from(this.selectedOptions).map(x=>x.value??x.text))">
                                        <?php
                                        foreach ($productsData as $proData) {
                                        ?>
                                            <option value="<?= $proData['sku'] ?>" selected><?= $proData['name'] ?></option>
                                        <?php }
                                        ?>
                                    </select>

                                    <input type="hidden" name="skus" id="skus" value="<?= $selectedSkus ?>" />
                                    <i class="fa fa-plus add_fields"></i>
                                    <div class="result"></div>
                                </div>
                            </div>
                        </div>
                        
                                       
                                   <div class="input-box" style="clear: both;">
                                       <div class="modelno-repeat">
                                           <div class="search-box">
                                               <input type="text" name="sm_email" style="height:32px" id="sales-man-email" autocomplete="off" placeholder="Sales manager email..." title="" value="<?php
                                                                                                                                                                                                               if (isset($_GET['sm_email']) && !empty($_GET['sm_email'])) {
                                                                                                                                                                                                                   echo $_GET['sm_email'];
                                                                                                                                                                                                               } else {
                                                                                                                                                                                                                   echo '';
                                                                                                                                                                                                               } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                               <div id="SMDropdown" class="dropdown-content">
                                                   <div id="dropdown-values-sm" class="dropdown-values">

                                                   </div>
                                               </div>
                                           </div>
                                       </div>
                                   </div>
                                   <div class="input-box" style="clear: both;">
                                       <div class="modelno-repeat">
                                           <div class="search-box">
                                               <input type="text" name="tm_email" style="height:32px" id="territory-man-email" autocomplete="off" placeholder="Territory manager email..." title="" value="<?php
                                                                                                                                                                                                                       if (isset($_GET['tm_email']) && !empty($_GET['tm_email'])) {
                                                                                                                                                                                                                           echo $_GET['tm_email'];
                                                                                                                                                                                                                       } else {
                                                                                                                                                                                                                           echo '';
                                                                                                                                                                                                                       } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                               <div id="TMDropdown" class="dropdown-content">
                                                   <div id="dropdown-values-tm" class="dropdown-values">

                                                   </div>
                                               </div>
                                           </div>
                                       </div>
                                   </div>
                                   <div class="input-box" style="clear: both;">
                                       <div class="modelno-repeat">
                                           <div class="search-box">
                                               <input type="text" name="em_email" style="height:32px" id="executive-man-email" autocomplete="off" placeholder="Executive manager email..." title="" value="<?php
                                                                                                                                                                                                                       if (isset($_GET['em_email']) && !empty($_GET['em_email'])) {
                                                                                                                                                                                                                           echo $_GET['em_email'];
                                                                                                                                                                                                                       } else {
                                                                                                                                                                                                                           echo '';
                                                                                                                                                                                                                       } ?>" data-validate="{required:true}" class="input-text required-entry" />
                                               <div id="EMDropdown" class="dropdown-content">
                                                   <div id="dropdown-values-em" class="dropdown-values">

                                                   </div>
                                               </div>
                                           </div>
                                       </div>
                                   </div>
                    
                        <button class="btn btn-primary" name="search" type="submit"><span class="glyphicon glyphicon-search"></span> Search</button>
                        <button id="export_data" name="export_data" class="button-import" type="submit"> Export Data</button>
                        
                    </div>
                </div>
            </div>
            </br>
            </br>
            </br>
            <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>


    <?php }
    }
    ?>
</form>
<script>
    var style = document.createElement('style');
    style.setAttribute("id", "multiselect_dropdown_styles");
    style.innerHTML = `
.multiselect-dropdown{
  display: inline-block;
  padding: 2px 5px 0px 5px;
  border-radius: 4px;
  border: solid 1px #ced4da;
  background-color: white;
  position: relative;
  background-repeat: no-repeat;
  background-position: right .75rem center;
  background-size: 16px 12px;
}
.multiselect-dropdown span.optext, .multiselect-dropdown span.placeholder{
  margin-right:0.5em;
  margin-bottom:2px;
  padding:1px 0;
  border-radius: 4px;
  display:inline-block;
}
.multiselect-dropdown span.optext{
  background-color:lightgray;
  padding:1px 0.75em;
}
.multiselect-dropdown span.optext .optdel {
  float: right;
  margin: 0 -6px 1px 5px;
  font-size: 0.7em;
  margin-top: 2px;
  cursor: pointer;
  color: #666;
}
.multiselect-dropdown span.optext .optdel:hover { color: #c66;}
.multiselect-dropdown span.placeholder{
  color:#ced4da;
}
.multiselect-dropdown-list-wrapper{
  box-shadow: gray 0 3px 8px;
  z-index: 100;
  padding:2px;
  border-radius: 4px;
  border: solid 1px #ced4da;
  display: none;
  margin: -1px;
  position: absolute;
  top:0;
  left: 0;
  right: 0;
  background: white;
}
.multiselect-dropdown-list-wrapper .multiselect-dropdown-search{
  margin-bottom:5px;
}
.multiselect-dropdown-list{
  padding:2px;
  height: 15rem;
  overflow-y:auto;
  overflow-x: hidden;
}
.multiselect-dropdown-list::-webkit-scrollbar {
  width: 6px;
}
.multiselect-dropdown-list::-webkit-scrollbar-thumb {
  background-color: #bec4ca;
  border-radius:3px;
}

.multiselect-dropdown-list div{
  padding: 5px;
}
.multiselect-dropdown-list input{
  height: 1.15em;
  width: 1.15em;
  margin-right: 0.35em;
}
.multiselect-dropdown-list div.checked{
}
.multiselect-dropdown-list div:hover{
  background-color: #ced4da;
}
.multiselect-dropdown span.maxselected {width:100%;}
.multiselect-dropdown-all-selector {border-bottom:solid 1px #999;}
`;
    document.head.appendChild(style);

    function MultiselectDropdown(options) {
        var config = {
            search: true,
            height: '15rem',
            placeholder: 'Products',
            txtSelected: 'selected',
            txtAll: 'All',
            txtRemove: 'Remove',
            txtSearch: 'search',
            ...options
        };

        function newEl(tag, attrs) {

            var e = document.createElement(tag);
            if (attrs !== undefined) Object.keys(attrs).forEach(k => {
                if (k === 'class') {
                    Array.isArray(attrs[k]) ? attrs[k].forEach(o => o !== '' ? e.classList.add(o) : 0) : (attrs[k] !== '' ? e.classList.add(attrs[k]) : 0)
                } else if (k === 'style') {
                    Object.keys(attrs[k]).forEach(ks => {
                        e.style[ks] = attrs[k][ks];
                    });
                } else if (k === 'text') {
                    attrs[k] === '' ? e.innerHTML = '&nbsp;' : e.innerText = attrs[k]
                } else e[k] = attrs[k];
            });
            return e;
        }


        document.querySelectorAll("select[multiple]").forEach((el, k) => {
            var div = newEl('div', {
                class: 'multiselect-dropdown',
                style: {
                    width: config.style?.width ?? el.clientWidth + 'px',
                    padding: config.style?.padding ?? ''
                }
            });
            el.style.display = 'none';
            el.parentNode.insertBefore(div, el.nextSibling);
            var listWrap = newEl('div', {
                class: 'multiselect-dropdown-list-wrapper'
            });
            var list = newEl('div', {
                class: 'multiselect-dropdown-list',
                id: ['multiselect-dropdown-list-id'],
                style: {
                    height: config.height
                }
            });
            var search = newEl('input', {
                class: ['multiselect-dropdown-search'].concat([config.searchInput?.class ?? 'form-control']),
                id: ['product-sku-input'],
                style: {
                    width: '100%',
                    display: el.attributes['multiselect-search']?.value === 'true' ? 'block' : 'none'
                },
                placeholder: config.txtSearch
            });
            listWrap.appendChild(search);
            div.appendChild(listWrap);
            listWrap.appendChild(list);

            el.loadOptions = () => {
                list.innerHTML = '';

                if (el.attributes['multiselect-select-all']?.value == 'true') {
                    var op = newEl('div', {
                        class: 'multiselect-dropdown-all-selector'
                    })
                    var ic = newEl('input', {
                        type: 'checkbox'
                    });
                    op.appendChild(ic);
                    op.appendChild(newEl('label', {
                        text: config.txtAll
                    }));

                    op.addEventListener('click', () => {
                        op.classList.toggle('checked');
                        op.querySelector("input").checked = !op.querySelector("input").checked;

                        var ch = op.querySelector("input").checked;
                        list.querySelectorAll(":scope > div:not(.multiselect-dropdown-all-selector)")
                            .forEach(i => {
                                if (i.style.display !== 'none') {
                                    i.querySelector("input").checked = ch;
                                    i.optEl.selected = ch
                                }
                            });

                        el.dispatchEvent(new Event('change'));
                    });
                    ic.addEventListener('click', (ev) => {
                        ic.checked = !ic.checked;
                    });
                    el.addEventListener('change', (ev) => {
                        let itms = Array.from(list.querySelectorAll(":scope > div:not(.multiselect-dropdown-all-selector)")).filter(e => e.style.display !== 'none')
                        let existsNotSelected = itms.find(i => !i.querySelector("input").checked);
                        if (ic.checked && existsNotSelected) ic.checked = false;
                        else if (ic.checked == false && existsNotSelected === undefined) ic.checked = true;
                    });

                    list.appendChild(op);
                }

                Array.from(el.options).map(o => {
                    var op = newEl('div', {
                        class: o.selected ? 'checked' : '',
                        optEl: o
                    })
                    var ic = newEl('input', {
                        type: 'checkbox',
                        checked: o.selected
                    });
                    op.appendChild(ic);
                    op.appendChild(newEl('label', {
                        text: o.text
                    }));

                    op.addEventListener('click', () => {
                        op.classList.toggle('checked');
                        op.querySelector("input").checked = !op.querySelector("input").checked;
                        op.optEl.selected = !!!op.optEl.selected;
                        el.dispatchEvent(new Event('change'));
                    });
                    ic.addEventListener('click', (ev) => {
                        ic.checked = !ic.checked;
                    });
                    o.listitemEl = op;
                    list.appendChild(op);
                });
                div.listEl = listWrap;

                div.refresh = () => {
                    div.querySelectorAll('span.optext, span.placeholder').forEach(t => div.removeChild(t));
                    var sels = Array.from(el.selectedOptions);
                    if (sels.length > (el.attributes['multiselect-max-items']?.value ?? 5)) {
                        div.appendChild(newEl('span', {
                            class: ['optext', 'maxselected'],
                            text: sels.length + ' ' + config.txtSelected
                        }));
                    } else {
                        sels.map(x => {
                            var c = newEl('span', {
                                class: 'optext',
                                text: x.text,
                                srcOption: x
                            });
                            if ((el.attributes['multiselect-hide-x']?.value !== 'true'))
                                c.appendChild(newEl('span', {
                                    class: 'optdel',
                                    text: '🗙',
                                    title: config.txtRemove,
                                    onclick: (ev) => {
                                        c.srcOption.listitemEl.dispatchEvent(new Event('click'));
                                        div.refresh();
                                        ev.stopPropagation();
                                    }
                                }));

                            div.appendChild(c);
                        });
                    }
                    if (0 == el.selectedOptions.length) div.appendChild(newEl('span', {
                        class: 'placeholder',
                        text: el.attributes['placeholder']?.value ?? config.placeholder
                    }));
                };
                div.refresh();
            }
            el.loadOptions();

            search.addEventListener('input', () => {
                // multiple select by ajax function
                var sku = document.getElementById('product-sku-input').value;
                getProducts(sku, sku.length);

                list.querySelectorAll(":scope div:not(.multiselect-dropdown-all-selector)").forEach(d => {
                    var txt = d.querySelector("label").innerText.toUpperCase();
                    d.style.display = txt.includes(search.value.toUpperCase()) ? 'block' : 'none';
                });
            });

            div.addEventListener('click', () => {
                div.listEl.style.display = 'block';
                search.focus();
                search.select();
            });

            document.addEventListener('click', function(event) {
                if (!div.contains(event.target)) {
                    listWrap.style.display = 'none';
                    div.refresh();
                }
            });
        });
    }

    window.addEventListener('load', () => {
        MultiselectDropdown(window.MultiselectDropdownOptions);
    });

    function getProducts(name, length) {
        require(['jquery'], function($) {
            if (length >= 3) {
                var id;
                var selectedSku = $("#skus").val();
                var customurl = "<?php echo $this->getUrl('adminreports/reports/productfilter') ?>";
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        sku: name,
                        selectedSku: selectedSku,
                    },
                    complete: function(response) {
                        if (response.responseJSON.success) {
                            // remove unchecked product select options
                            removeUncheckedOptions($);

                            // $('#field2').append('<option value="COAM" selected>COAM</option>');
                            $("#multiselect-dropdown-list-id").append(response.responseJSON.products);
                        } else {
                            // remove unchecked product select options
                            removeUncheckedOptions($);
                            console.log('Error happens. Try again.');
                        }
                    },
                    error: function(xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            } else {
                // remove unchecked product select options
                removeUncheckedOptions($);
            }
        });
    }
    // check box on change finction
    function addSelectOption(sku, name, id) {
        require(['jquery'], function($) {
            var checkbox = $(id).val();
            if (checkbox == 'false') {
                $(id).val('true');
                $('#field2').append('<option value="' + sku + '" selected>' + name + '</option>');
            } else {
                $("option[value='" + sku + "']").remove();
                $(id).val('false');
            }
            var select = document.getElementById('field2');
            var skus = [...select.selectedOptions]
                .map(option => option.value);
            document.getElementById("skus").value = skus;
            console.log(skus);
        })
    }

    // remove unchecked product select options function
    function removeUncheckedOptions($) {
        $("#multiselect-dropdown-list-id :input").each(function(e) {
            id = this.id;
            value = this.value;
            if (value == 'false') {
                $("#class-" + id).remove();
            }
        });
    }
</script>
<script>
    require(['jquery'], function($) {
        // Sales Rep Email JS
        $('#sales-rep-email').click(function() {
            $("#dropdown-values-sr").addClass("show");
        });

        $(document).click(function(e) {
            if (e.target.id != 'sales-rep-email') {
                $("#dropdown-values-sr").removeClass("show");
            }
        });

        $('#sales-rep-email').keyup(function() {
            $("#dropdown-values-sr").empty();
            var sales_rep_email = $('#sales-rep-email').val();
            if (sales_rep_email.length >= 3) {
                var customurl = "<?php echo $this->getUrl('adminreports/reports/emailfilter') ?>";
                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        salesrep_email: sales_rep_email,
                    },
                    complete: function(response) {
                        if (response.responseJSON.success) {
                            $("#dropdown-values-sr").empty();
                            $("#dropdown-values-sr").append(response.responseJSON.customers);
                        } else {
                            console.log('Error happens in Sales Rep Email. Try again.');
                        }
                    },
                    error: function(xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            }
        });
            
        // Sales Manager Email JS
               $('#sales-man-email').click(function() {
                   $("#dropdown-values-sm").addClass("show");
               });

               $(document).click(function(e) {
                   if (e.target.id != 'sales-man-email') {
                       $("#dropdown-values-sm").removeClass("show");
                   }
               });

               $('#sales-man-email').keyup(function() {
                   $("#dropdown-values-sm").empty();
                   var salesmanager_email = $('#sales-man-email').val();
                   if (salesmanager_email.length >= 3) {
                       var customurl = "<?php echo $this->getUrl('adminreports/reports/emailfilter') ?>";
                       $.ajax({
                           url: customurl,
                           type: 'POST',
                           dataType: 'json',
                           data: {
                               salesmanager_email: salesmanager_email,
                           },
                           complete: function(response) {
                               if (response.responseJSON.success) {
                                   $("#dropdown-values-sm").empty();
                                   $("#dropdown-values-sm").append(response.responseJSON.customers);
                               } else {
                                   console.log('Error happens in Sales Manager Email. Try again.');
                               }
                           },
                           error: function(xhr, status, errorThrown) {
                               console.log('Error happens. Try again.');
                           }
                       });
                   }
               });
               // End Sales Manager Email JS

               // Territory Manager Email JS
               $('#territory-man-email').click(function() {
                   $("#dropdown-values-tm").addClass("show");
               });

               $(document).click(function(e) {
                   if (e.target.id != 'territory-man-email') {
                       $("#dropdown-values-tm").removeClass("show");
                   }
               });

               $('#territory-man-email').keyup(function() {
                   $("#dropdown-values-tm").empty();
                   var territorymanager_email = $('#territory-man-email').val();
                   if (territorymanager_email.length >= 3) {
                       var customurl = "<?php echo $this->getUrl('adminreports/reports/emailfilter') ?>";
                       $.ajax({
                           url: customurl,
                           type: 'POST',
                           dataType: 'json',
                           data: {
                               territorymanager_email: territorymanager_email,
                           },
                           complete: function(response) {
                               if (response.responseJSON.success) {
                                   $("#dropdown-values-tm").empty();
                                   $("#dropdown-values-tm").append(response.responseJSON.customers);
                               } else {
                                   console.log('Error happens in Territory Manager Email. Try again.');
                               }
                           },
                           error: function(xhr, status, errorThrown) {
                               console.log('Error happens. Try again.');
                           }
                       });
                   }
               });
               // End Territory Manager Email JS

               // Executive Manager Email JS

               $('#executive-man-email').click(function() {
                   $("#dropdown-values-em").addClass("show");
               });

               $(document).click(function(e) {
                   if (e.target.id != 'executive-man-email') {
                       $("#dropdown-values-em").removeClass("show");
                   }
               });

               $('#executive-man-email').keyup(function() {
                   $("#dropdown-values-em").empty();
                   var executivemanager_email = $('#executive-man-email').val();
                   if (executivemanager_email.length >= 3) {
                       var customurl = "<?php echo $this->getUrl('adminreports/reports/emailfilter') ?>";
                       $.ajax({
                           url: customurl,
                           type: 'POST',
                           dataType: 'json',
                           data: {
                               executivemanager_email: executivemanager_email,
                           },
                           complete: function(response) {
                               if (response.responseJSON.success) {
                                   $("#dropdown-values-em").empty();
                                   $("#dropdown-values-em").append(response.responseJSON.customers);
                               } else {
                                   console.log('Error happens in Executive Manager Email. Try again.');
                               }
                           },
                           error: function(xhr, status, errorThrown) {
                               console.log('Error happens. Try again.');
                           }
                       });
                   }
               });
        
        // End Executive ManagerEmail JS
    });
    // Sales Rep Set value function
    function setSRValueOfInput(e) {
        document.getElementById("sales-rep-email").value = e.innerHTML;
    }
    // Sales Manager Set value function
    function setSMValueOfInput(e) {
        document.getElementById("sales-man-email").value = e.innerHTML;
    }

    // Territory Manager Set value function
    function setTMValueOfInput(e) {
        document.getElementById("territory-man-email").value = e.innerHTML;
    }

    // Executive Manager Set value function
    function setEMValueOfInput(e) {
        document.getElementById("executive-man-email").value = e.innerHTML;
    }
</script>

