<style>
* {
  box-sizing: border-box;
}

.column {
  float: left;
  width: 48%;
  padding: 20px;
  /* height: 260px; */
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

.field {
  margin: 0 0 10px;
}

.required-field::after {
  content: "*";
  color: red;
  margin-left:2px
}
</style>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
if(isset($_GET['ae_id'])) {
 $id = $_GET['ae_id'];
 $data = $block->getAEDetail($id);
 if($data['sales_order']){
 $position = strpos($data['sales_order'], 'SO');
 $number=explode(",",substr($data['sales_order'],$position));
 $SONumber = $block->getOrderCollectionBySONumber($number);
;
if($data) {
  $customUrl=$this->getUrl('nsconnector/rma/index/').'?rma_id='.$data['return_authorization_nsid'].'&ae_id='.$id;
  if($SONumber){
    $customUrls=$this->getUrl('sales/order/view/order_id/'.$SONumber);
  }
  else{
    
    $customUrls=$this->getUrl('advanceexchange/manage/emptyorder').'?ae_id='.$id;
}
}

?>

<div class="row">
<h2 style="background-color:lightgray; padding: 16px;"> Primary Information</h2>
  <div class="column">
    <p><b>ADVANCED EXCHANGE TYPE: </b><?=$data['exchangetype']?></p>
    <p><b>CASE NUMBER: </b><?=$data['casenumber']?></p>
    
    <p><b>DESCRIPTION: </b><?=$data['msgdescription']?></p>
    <p><b>DEVICE IMEI ENROLLED/VALIDATED: </b><?= ($data['imeienrolled'] == 1) ? 'Yes' : 'No'; ?></p>
    <p><b>SERIAL NUMBER OF DEVICE: </b><?=$data['deviceimei']?></p>
    <p><b>CONNECTIVITY ISSUE: </b><?=$data['damagereason']?></p>
    <p><b>SIM OF DEVICE: </b><?=$data['simofdevice']?></p>
    <p><b>REQUEST RETURN SHIPPING LABEL: </b><?= ($data['returnshippinglabel'] == 1) ? 'Yes' : 'No'; ?></p>
    <p><b>COST CENTER/DEPARTMENT: </b><?=$data['costcenter']?></p>

  </div> 
  
  <div class="column">
  <p><b>COMPANY: </b><?=$data['company_name']?></p>
    <p><b>SUBSIDIARY: </b><?=$data['subsidiary_name']?></p>
    <p><b>ASSIGNED TO: </b><?=$data['assigned_name']?></p>
    <p><b>CASE ITEM: </b><?=$data['msgsku']?></p>
    <p><b>STATUS: </b><?=$data['case_status']?></p>
    <p><b>SUBMITTER FIRST NAME: </b><?=$data['submitterfirstname']?></p>
    <p><b>SUBMITTER LAST NAME: </b><?=$data['submitterlastname']?></p>
    <p><b>SUBMITTER EMAIL: </b><?=$data['submitteremail']?></p>
    <p><b>SUBMITTER PHONE NUMBER: </b><?= $data['submitterphone'] ?></p>
  </div>
  </div>

    <div class="row">
      <h2 style="background-color:lightgray; padding: 16px;"> Advanced Device Details</h2>
      <div class="column">
    <p><b>SHIP TO SELECT: </b><?=$data['shiptoselect']?></p>
    <p><b>SHIP TO ADDRESS LABEL/NAME: </b><?=$data['shiptoaddresslabel']?></p>
    <p><b>SHIP TO ATTENTION: </b><?=$data['shiptoattention']?></p>
    <p><b>SHIP TO STREET ADDRESS 1: </b><?=$data['shiptostreet']?></p>
    <p><b>SHIP TO STREET ADDRESS 2: </b><?=$data['shiptostreet2']?></p>
    <p><b>SHIP TO CITY: </b><?=$data['shiptocity']?></p>
    <p><b>SHIP TO STATE: </b><?=$data['shiptostate']?></p>
    
  </div>

  <div class="column">
  <p><b>SHIP TO ZIP CODE: </b><?=$data['shiptozip']?></p>
    <p><b>SALES ORDER: </b><a href="<?php echo $customUrls ?>"><?=$data['sales_order']?></a></p>
    <p><b>INVOICE: </b><?=$data['case_invoice']?></p>
    <p><b>SAVE ADDRESS ON FILE: </b><?= ($data['saveaddress'] == 1) ? 'Yes' : 'No'; ?></p>
    <p><b>SHIPPING ACCOUNT # : </b><?=$data['shippingaccountno']?></p>
    <p><b>DAMAGE/REASON: </b><?=$data['damagereason']?></p>
    <?php if($data['attachedfile']) { ?>
    <p><b>FILE ATTACHMENT: </b><a href="<?=$baseUrl.$data['attachedfile']?>" target="_blank">View File</a></p>
    <?php } ?>
</div>
</div>
<div class="row">
  <h2 style="background-color:lightgray; padding: 16px;"> Return Label</h2>
      <div class="column">
    <p><b>SHIPPING LABEL ADDRESS SELECT: </b><?=$data['shiplabelselect']?></p>
    <p><b>SHIPPING LABEL ATTENTION: </b><?=$data['shiplabelattention']?></p>
    <p><b>SHIPPING LABEL STREET ADDRESS 1: </b><?=$data['shiptostreet']?></p>
    <p><b>SHIPPING LABEL STREET ADDRESS 2: </b><?=$data['shiplabelstreet2']?></p>
    <p><b>SHIPPING LABEL CITY: </b><?=$data['shiptocity']?></p>
    <p><b>SAME AS SHIP TO ADDRESS: </b><?= ($data['sameasship'] == 1) ? 'Yes' : 'No'; ?></p>

   
  </div>
    <div class="column">
    <p><b>RETURN AUTHORIZATION: </b><a href="<?php echo $customUrl ?>"><?=$data['return_authorization']?></a></p>
    <p><b>SHIPPING LABEL STATE: </b><?=$data['shiptostate']?></p>
    <p><b>SHIPPING LABEL ZIP CODE: </b><?=$data['shiptozip']?></p>
    <p><b>INBOUND TRACKING NUMBER(BROKEN DEVICE): </b><?=$data['case_inbound_tracking_value']?></p>
   
  </div>
    </div>

<?php } } ?>
