<style>
  * {
    box-sizing: border-box;
  }

  .column {
    float: left;
    width: 20%;
    padding: 10px;
  }

  .row:after {
    content: "";
    display: table;
    clear: both;
  }

  .field {
    margin: 0 0 10px;
  }

  .required-field::after {
    content: "*";
    color: red;
    margin-left: 2px
  }
</style>

<?php
// 

//
$skus = $block->getSkus();
$cid = $block->getCustomerId();
if ($cid) {
  $shippingAddress = $block->getShippingInfo($cid);
  $internalId = $block->getInternalId();
  $customer = $block->getCustomer($cid);
  $fname = $customer->getLastName();
  $lname = $customer->getFirstName();
  $email = $customer->getEmail();
  $custom_phone = $customer->getCustomAttribute('customer_phone');
  $allowDepotServiceType = $customer->getCustomAttribute('alwd_depot_service_type');
  $typeValues = array();
  if ($allowDepotServiceType) {
    $types = $allowDepotServiceType->getValue();
    $typeValues = explode(",", $types);
  }
  $phone = '';
  if ($custom_phone) {
    $phone = $custom_phone->getValue();
  }
?>

  <form action="" method="post" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>






    <div class="primary">
      <button type="submit" class="action save primary" title="Submit Request">
        <span>Submit Request</span>
      </button>
    </div>

    <input type="hidden" id="cid" name="cid" value="<?= $cid ?>">
    <input type="hidden" id="internalid" name="internalid" value="<?= $internalId ?>">
    <div class="row">
      <div class="column">
        <h3>Depot Service Type</h3>
        <b>Ship on Request</b>
        <p>Place an order to have a new device shipped to replace a broken device. New device will ship upon request submission.</p>
        <b>Ship on Return</b>
        <p>Place an order to have a new device shipped to replace a broken device. New device will ship once return tracking numbers shows shipped.</p>
        <b>Repair and Return</b>
        <p>Place a request for a device to be returned for repair and then shipped back.</p>
        <b>Lost or Stolen</b>
        <p>Request a new device to be shipped to replace a lost or stolen device. Requests must be approved by customer management.</p>
        <b>Return Request</b>
        <p>Request to have a device RMA generated.</p>
        <p> <i>Don’t see all of the above options? Contact your MCG Account Manager today to discuss our premium service offerings!</i></p>

      </div>

      <div class="column">
        <div class="field field-exchangetype-dropdown required">
          <label class="label required-field" for="exchangetype-dropdown"><span>DEPOT SERVICE TYPE</span></label>
          <div class="control">
            <select name="exchangetype" title="Depot Service Type" data-validate="{required:true}">
              <option value=""></option>
              <?php foreach ($typeValues as $typeValue) { ?>
                <option value="<?= $typeValue ?>"><?= $typeValue ?></option>
              <?php } ?>
            </select>
          </div>
        </div>

        <div class="field field-exchangetype-dropdown required">
          <label class="label required-field" for="msgsku-dropdown"><span>MSG SKU# </span></label>
          <div class="control">
            <select name="msgsku" title="MSG SKU# " data-validate="{required:true}">
              <?php if (count($skus) > 0) {
                foreach ($skus as $data) { ?>
                  <option value="<?= $data['sku'] ?>"><?= $data['sku'] ?> </option>
                <?php }
              } else { ?>
                <option value="-">- No Sku Found -</option>
              <?php } ?>
            </select>
          </div>
        </div>

        <div class="field field-description required">
          <label class="label" for="description"><span>DESCRIPTION</span></label>
          <div class="control">
            <textarea id="msgdescription" name="msgdescription" rows="4">
        </textarea>
          </div>
        </div>

        <div class="field choice">
          <input type="checkbox" name="imeienrolled" id="imeienrolled" data-role="imeienrolled" value="1" title="IMEI ENROLLED" class="checkbox">
          <label class="label" for="imeienrolled">
            <span>DEVICE IMEI ENROLLED/VALIDATED</span>
          </label>
        </div>

        <div class="field field-deviceimei required">
          <label class="label required-field" for="deviceimei"><span>RETURN DEVICE IMEI / SERIAL# </span></label>
          <div class="control">
            <input type="text" id="deviceimei" name="deviceimei" value="" title="RETURN DEVICE IMEI / SERIAL#" class="input-text" data-validate="{required:true}" aria-required="true">
          </div>
        </div>

        <div class="field field-deviceimei required">
          <label class="label" for="simofdevice"><span>SIM OF DEVICE</span></label>
          <div class="control">
            <input type="text" id="simofdevice" name="simofdevice" value="" title="SIM OF DEVICE" class="input-text" aria-required="true">
          </div>
        </div>

        <div class="field choice">
          <input type="checkbox" name="returnshippinglabel" id="returnshippinglabel" data-role="returnshippinglabel" value="1" title="REQUEST RETURN SHIPPING LABEL" class="checkbox">
          <label class="label" for="returnshippinglabel">
            <span>REQUEST RETURN SHIPPING LABEL</span>
          </label>
        </div>
      </div>

      <div class="column">
        <div class="field field-submitterfirstname required">
          <label class="label required-field" for="submitterfirstname"><span>SUBMITTER FIRST NAME</span></label>
          <div class="control">
            <input type="text" id="submitterfirstname" name="submitterfirstname" value="<?= $fname ?>" title="SUBMITTER FIRST NAME" class="input-text" data-validate="{required:true}" aria-required="true">
          </div>
        </div>

        <div class="field field-submitterlastname required">
          <label class="label required-field" for="submitterlastname"><span>SUBMITTER LAST NAME</span></label>
          <div class="control">
            <input type="text" id="submitterlastname" name="submitterlastname" value="<?= $lname ?>" title="SUBMITTER LAST NAME" class="input-text" data-validate="{required:true}" aria-required="true">
          </div>
        </div>

        <div class="field field-submitteremail required">
          <label class="label required-field" for="submitteremail"><span>SUBMITTER EMAIL</span></label>
          <div class="control">
            <input type="text" id="submitteremail" name="submitteremail" value="<?= $email ?>" title="SUBMITTER EMAIL" class="input-text validate-email" data-validate="{required:true}" aria-required="true">
          </div>
        </div>

        <div class="field field-submitterphone required">
          <label class="label required-field" for="submitterphone"><span>SUBMITTER PHONE NUMBER</span></label>
          <div class="control">
            <input type="text" id="submitterphone" name="submitterphone" value="<?= $phone ?>" title="SUBMITTER PHONE NUMBER" class="input-text" data-validate="{required:true}" aria-required="true">
          </div>
        </div>

        <div class="field field-costcenter required">
          <label class="label required-field" for="costcenter"><span>COST CENTER/DEPARTMENT</span></label>
          <div class="control">
            <input type="text" id="costcenter" name="costcenter" value="" title="COST CENTER/DEPARTMENT" class="input-text" data-validate="{required:true}" aria-required="true">
          </div>
        </div>
      </div>

      <div class="column">
        <div class="field field-shiptoselect-dropdown required">
          <label class="label" for="shiptoselect-dropdown"><span>SHIP TO SELECT</span></label>
          <div class="control">
            <select class="shiptoselect" name="shiptoselect" title="SHIP TO SELECT">
              <option value="new">Add New Address</option>
              <option value="default">Select Existing Address</option>
            </select>
          </div>
        </div>

        <div id="newaddress" class="newaddress">
          <div class="field field-shiptoaddresslabelr required">
            <label class="label" for="shiptoaddresslabel"><span>SHIP TO ADDRESS LABEL/NAME</span></label>
            <div class="control">
              <input type="text" id="shiptoaddresslabel" name="shiptoaddresslabel" value="" title="SHIP TO ADDRESS LABEL/NAME" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptoattention required">
            <label class="label" for="shiptoattention"><span>SHIP TO ATTENTION</span></label>
            <div class="control">
              <input type="text" id="shiptoattention" name="shiptoattention" value="" title="SHIP TO ATTENTION" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptostreet required">
            <label class="label" for="shiptostreet"><span>SHIP TO STREET ADDRESS 1</span></label>
            <div class="control">
              <input type="text" id="shiptostreet" name="shiptostreet" value="" title="SHIP TO STREET ADDRESS 1" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptostreet2 required">
            <label class="label" for="shiptostreet2"><span>SHIP TO STREET ADDRESS 2</span></label>
            <div class="control">
              <input type="text" id="shiptostreet2" name="shiptostreet2" value="" title="SHIP TO STREET ADDRESS 2" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptocity required">
            <label class="label" for="shiptocity"><span>SHIP TO CITY</span></label>
            <div class="control">
              <input type="text" id="shiptocity" name="shiptocity" value="" title="SHIP TO CITY" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptostate required">
            <label class="label" for="shiptostate"><span>SHIP TO STATE</span></label>
            <div class="control">
              <input type="text" id="shiptostate" name="shiptostate" value="" title="SHIP TO STATE" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptozip required">
            <label class="label" for="shiptozip"><span>SHIP TO ZIP CODE</span></label>
            <div class="control">
              <input type="text" id="shiptozip" name="shiptozip" value="" title="SHIP TO ZIP CODE" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field choice">
            <input type="checkbox" name="saveaddress" id="saveaddress" data-role="saveaddress" value="1" title="SAVE ADDRESS ON FILE" class="checkbox">
            <label class="label" for="saveaddress">
              <span>SAVE ADDRESS ON FILE (NEW ADDRESS ONLY)</span>
            </label>
          </div>
        </div>

        <div id="defaultaddress" class="defaultaddress" style="display:none">
          <div class="field field-shiptoaddresslabelr required">
            <label class="label" for="shiptoaddresslabel"><span>SHIP TO ADDRESS LABEL/NAME</span></label>
            <div class="control">
              <input type="text" id="shiptoaddresslabel" name="shiptoaddresslabeld" value="<?= $shippingAddress['shippingLabel'] ?>" title="SHIP TO ADDRESS LABEL/NAME" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptoattention required">
            <label class="label" for="shiptoattention"><span>SHIP TO ATTENTION</span></label>
            <div class="control">
              <input type="text" id="shiptoattention" name="shiptoattentiond" value="<?= $shippingAddress['shippingLabel'] ?>" title="SHIP TO ATTENTION" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptostreet required">
            <label class="label" for="shiptostreet"><span>SHIP TO STREET ADDRESS 1</span></label>
            <div class="control">
              <input type="text" id="shiptostreet" name="shiptostreetd" value="<?= $shippingAddress['shippingStreet1'] ?>" title="SHIP TO STREET ADDRESS 1" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptostreet2 required">
            <label class="label" for="shiptostreet2"><span>SHIP TO STREET ADDRESS 2</span></label>
            <div class="control">
              <input type="text" id="shiptostreet2" name="shiptostreet2d" value="<?= $shippingAddress['shippingStreet2'] ?>" title="SHIP TO STREET ADDRESS 2" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptocity required">
            <label class="label" for="shiptocity"><span>SHIP TO CITY</span></label>
            <div class="control">
              <input type="text" id="shiptocity" name="shiptocityd" value="<?= $shippingAddress['shippingCity'] ?>" title="SHIP TO CITY" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptostate required">
            <label class="label" for="shiptostate"><span>SHIP TO STATE</span></label>
            <div class="control">
              <input type="text" id="shiptostate" name="shiptostated" value="<?= $shippingAddress['shippingState'] ?>" title="SHIP TO STATE" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field field-shiptozip required">
            <label class="label" for="shiptozip"><span>SHIP TO ZIP CODE</span></label>
            <div class="control">
              <input type="text" id="shiptozip" name="shiptozipd" value="<?= $shippingAddress['shippingZip'] ?>" title="SHIP TO ZIP CODE" class="input-text" aria-required="true">
            </div>
          </div>

          <div class="field choice">
            <input type="checkbox" name="saveaddressd" id="saveaddress" data-role="saveaddress" value="1" title="SAVE ADDRESS ON FILE" class="checkbox">
            <label class="label" for="saveaddress">
              <span>SAVE ADDRESS ON FILE (NEW ADDRESS ONLY)</span>
            </label>
          </div>
        </div>
      </div>

      <!-- <div class="column">
    <div class="field field-shiplabelselect-dropdown required">
      <label class="label" for="shiplabelselect-dropdown"><span>SHIPPING LABEL ADDRESS SELECT</span></label>
      <div class="control">
        <select name="shiplabelselect" title="SHIPPING LABEL ADDRESS SELECT">
          <option value="Add New Address">Add New Address</option>
        </select>
      </div>
    </div>
   
    <div class="field field-shiplabelattention required">
      <label class="label" for="shiplabelattention"><span>SHIPPING LABEL ATTENTION</span></label>
      <div class="control">
          <input type="text" id="shiplabelattention" name="shiplabelattention" value="" title="SHIPPING LABEL ATTENTION" class="input-text" aria-required="true">
      </div>
    </div>

    <div class="field field-shiplabelstreet required">
      <label class="label" for="shiplabelstreet"><span>SHIPPING LABEL STREET ADDRESS 1</span></label>
      <div class="control">
          <input type="text" id="shiplabelstreet" name="shiplabelstreet" value="" title="SHIPPING LABEL STREET ADDRESS 1" class="input-text" aria-required="true">
      </div>
    </div>

    <div class="field field-shiplabelstreet2 required">
      <label class="label" for="shiplabelstreet2"><span>SHIPPING LABEL STREET ADDRESS 2</span></label>
      <div class="control">
          <input type="text" id="shiplabelstreet2" name="shiplabelstreet2" value="" title="SHIPPING LABEL STREET ADDRESS 2" class="input-text" aria-required="true">
      </div>
    </div>

    <div class="field field-shiplabelcity required">
      <label class="label" for="shiplabelcity"><span>SHIPPING LABEL CITY</span></label>
      <div class="control">
          <input type="text" id="shiplabelcity" name="shiplabelcity" value="" title="SHIPPING LABEL CITY" class="input-text" aria-required="true">
      </div>
    </div>

    <div class="field field-shiplabelstate required">
      <label class="label" for="shiplabelstate"><span>SHIPPING LABEL STATE</span></label>
      <div class="control">
          <input type="text" id="shiplabelstate" name="shiplabelstate" value="" title="SHIPPING LABEL STATE" class="input-text" aria-required="true">
      </div>
    </div>

    <div class="field field-shiplabelzip required">
      <label class="label" for="shiplabelzip"><span>SHIPPING LABEL ZIP CODE</span></label>
      <div class="control">
          <input type="text" id="shiplabelzip" name="shiplabelzip" value="" title="SHIPPING LABEL ZIP CODE" class="input-text" aria-required="true">
      </div>
    </div>

    <div class="field choice">
      <input type="checkbox" name="sameasship" id="sameasship" data-role="sameasship" value="1" title="SAME AS SHIP TO ADDRESS" class="checkbox">
      <label class="label" for="sameasship">
          <span>SAME AS SHIP TO ADDRESS</span>
      </label>
    </div>
  </div> -->

      <div class="column">
        <div class="field field-shippingaccountno required">
          <label class="label" for="shippingaccountno"><span>SHIPPING ACCOUNT # </span></label>
          <div class="control">
            <input type="text" id="shippingaccountno" name="shippingaccountno" value="" title="SHIPPING ACCOUNT # " class="input-text" aria-required="true">
          </div>
        </div>

        <div class="field field-damagereason required">
          <label class="label required-field" for="damagereason"><span>DAMAGE/REASON</span></label>
          <div class="control">
            <select name="damagereason[]" id="damagereason" data-validate="{required:true}" multiple="multiple">
              <option value="new">- New -</option>
              <option value="Attack Code Detected">Attack Code Detected</option>
              <option value="Battery Issues">Battery Issues (swelling, limited capacity, doesn't charge, etc.)</option>
              <option value="Broken Screen">Broken Screen</option>
              <option value="Button Failure">Button Failure</option>
              <option value="Camera Issues">Camera Issues</option>
              <option value="Charging Port Issue">Charging Port Issue</option>
              <option value="Connectivity Issues">Connectivity Issues</option>
              <option value="Magnetic Card Failure">Magnetic Card Failure</option>
              <option value="Power Issues">Power Issues</option>
              <option value="Return Only">Return Only (No Issues)</option>
              <option value="Screen Damage">Screen Damage</option>
              <option value="Sim Slot Card Failure">Sim Slot Card Failure</option>
              <option value="Smart Card Failure">Smart Card Failure</option>
              <option value="Water Damage">Water Damage</option>
            </select>
          </div>
        </div>

        <div class="field field-attachedfile required">
          <label class="label" for="attachedfile"><span>FILE ATTACHMENT</span></label>
          <div class="control">
            <input type="file" id="attachedfile" name="attachedfile">
          </div>
        </div>
      </div>
  </form>
  </div>

  <script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($) {
      $(document).ready(function() {
        $('.shiptoselect').change(function() {
          var val = $(this).val();
          if (val == 'new') {
            $("#defaultaddress").css("display", "none");
            $("#newaddress").css("display", "block");
          }
          if (val == 'default') {
            $("#defaultaddress").css("display", "block");
            $("#newaddress").css("display", "none");
          }
        })
      });
    });
  </script>
<?php } ?>