<style>
    @media (min-width: 500px) {
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .column_total {
            font-weight: bold;
        }

        .row {
            padding-top: 25px;
        }

        .column-half {
            float: right;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }

        .button-import {
            white-space: nowrap;
            margin-left: 10px;
        }

        .button-pdf {
            white-space: nowrap;
            margin-left: 10px;
        }
        .scrollit {
            overflow-x:auto;
            white-space: nowrap;
            /* overscroll-behavior-x: contain; */
        }


    }
</style>

<?php
$data = $block->getAllRecords();
$cid = $block->getCustomerId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$paramtype = 'all';
$paramCaseStatus = 'all';
$paramApprovalStatus = 'all';

if (isset($_GET['exchangetype'])) {
    $paramtype = $_GET['exchangetype'];
}
if (isset($_GET['case_status'])) {
    $paramCaseStatus = $_GET['case_status'];
}
if (isset($_GET['approval_status'])) {
    $paramApprovalStatus = $_GET['approval_status'];
}
?>

<form method="GET" action="">
    <div class="row">
        <div class="column-half" style="width: 100%; display: flex;">
            <div class="selecttype-div">
                <select name="exchangetype" style="margin-left: 10px;width:150px" title="Exchange Type">
                    <option value="all" <?= $paramtype == 'all' ? 'selected' : '' ?>>Exchange Type</option>
                    <option value="repair" <?= $paramtype == 'repair' ? 'selected' : '' ?>>Repair & Return</option>
                    <option value="request" <?= $paramtype == 'request' ? 'selected' : '' ?>>Ship On Request</option>
                    <option value="return" <?= $paramtype == 'return' ? 'selected' : '' ?>>Ship On Return</option>
                    <option value="lost" <?= $paramtype == 'lost' ? 'selected' : '' ?>>Lost Or Stolen</option>
                    <button name='submit'> </button>
                </select>
            </div>
            <div class="selectcasestatus-div">
                <select name="case_status" style="margin-left: 10px;width:150px" title="Type">
                    <option value="all" <?= $paramCaseStatus == 'all' ? 'selected' : '' ?>>Case Status</option>
                    <option value="Closed" <?= $paramCaseStatus == 'Closed' ? 'selected' : '' ?>>Closed</option>
                    <option value="Completed" <?= $paramCaseStatus == 'Completed' ? 'selected' : '' ?>>Completed</option>
                    <option value="Cancelled" <?= $paramCaseStatus == 'Cancelled' ? 'selected' : '' ?>>Cancelled</option>
                </select>
            </div>
            <div class="selectapprovalstatus-div">
                <select name="approval_status" style="margin-left: 10px;width:150px" title="Type">
                    <option value="all" <?= $paramApprovalStatus == 'all' ? 'selected' : '' ?>>Approval Status</option>
                    <option value="pending" <?= $paramApprovalStatus == 'pending' ? 'selected' : '' ?>>Pending Approval</option>
                    <option value="Approved" <?= $paramApprovalStatus == 'Approved' ? 'selected' : '' ?>>Approved</option>
                </select>
            </div>
            <div class="submitbutton-div">
                <button type="submit" style="margin-left: 10px;width:100px">Submit</button>
            </div>
        </div>
    </div>



    <?php if (count($data) > 0) { ?>
        <div class="scrollit">
            
        <table class="data table table-order-items history" id="my-orders-table">
            <thead>
                <tr>
                <th scope="col" class="col casenumber"><?= $block->escapeHtml(__('Case Number')) ?></th>
                    <th scope="col" class="col msgsku"><?= $block->escapeHtml(__('MSG Sku#')) ?></th>
                    <!-- <th scope="col" class="col deviceimei"><?= '' //$block->escapeHtml(__('Serial#')) 
                                                                ?></th> -->
                    <th scope="col" class="col submitterfirstname"><?= $block->escapeHtml(__('First Name')) ?></th>
                    <th scope="col" class="col submitteremail"><?= $block->escapeHtml(__('Email')) ?></th>
                    <th scope="col" class="col exchangetype"><?= $block->escapeHtml(__('Exchange Type')) ?></th>
                    <th scope="col" class="col action">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($data as $ae) : //echo "<pre>";print_r($order->getData());die();
                ?>
                    <tr>
                    <td class="col casenumber"><?= $ae['casenumber'] ?></td>
                        <td class="col msgsku"><?= $ae['msgsku'] ?></td>
                        <!-- <td class="col deviceimei"><?= '' //$ae['deviceimei'] 
                                                        ?></td> -->
                        <td class="col submitterfirstname"><?= $ae['submitterfirstname'] ?></td>
                        <td class="col submitteremail"><?= $ae['submitteremail'] ?></td>
                        <td class="col exchangetype"><?= $ae['exchangetype'] ?></td>
                        <td class="col id"><a href="<?= $baseUrl ?>advanceexchange/manage/detail?ae_id=<?= $ae['advanced_exchange_id'] ?>">View Detail</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
                </div>
    <?php } else {
        echo "No Records Found";
    } ?>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom">
            <?= $block->getPagerHtml() ?>
        </div>
    <?php endif ?>


</form>