<style>
    @media (min-width: 500px) {
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .row {
            padding-top: 25px;
        }

        .column-half {
            float: left;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }
    }
</style>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$checkOutSession = $objectManager->create('Magento\Checkout\Model\Session');
$repository = $objectManager->create('Mobility\QuoteRequest\Model\QuoteRequestFactory');
$requestQuoteCollection = $repository->create()->getCollection();
$requestQuoteCollection->addFieldToFilter('quote_id', $checkOutSession->getQuoteId())->getFirstItem();
if ($requestQuoteCollection->getData()) {
    $formQuote = true;
} else {
    $formQuote = false;
}
$params = $request->getParams();
if (isset($params['mtel_id'])) {
    $MtelId = $params['mtel_id'];
    $data = $block->getByTrackingNo($MtelId);
    if ($customerSession->getCustomer()->getData('Customer_Type') != 1) {
        echo  '<p>Please, login as sales rep to continue.</p>';
    } elseif ($data->getData() && $data->getStatus() != 'converted') {

?>
        <div class="table-wrapper orders-history">
            <center>
                <table class="data table table-order-items history" id="my-orders-table">
                    <thead>
                        <tr>
                            <th scope="col"><?= 'ATTUID' ?></th>
                            <td class="col id"><?= $data->getAttuid() ?></td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Opportunity Name/Quote Name' ?></th>
                            <td class="col total"><?= $data->getQuoteName() ?></td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Saleforce Opporunity ID' ?></th>
                            <td class="col status"><?= $data->getSalesforceOpportunityId() ?></td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Length of Demo' ?></th>
                            <td class="col actions"><?= $data->getDemoLength() ?></td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Name of Agency' ?></th>
                            <td class="col date"><?= $data->getAgencyName() ?></td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'First Net Type' ?></th>
                            <td class="col actions"><?= $data->getFirstNetType() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Discipline' ?></th>
                            <td class="col actions"><?= $data->getDiscipline() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Customer Email Address' ?></th>
                            <td class="col actions"><?= $data->getCustomerEmail() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Customer Phone Number' ?></th>
                            <td class="col actions"><?= $data->getCustomerPhone() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Customer Name' ?></th>
                            <td class="col actions"><?= $data->getCustomerName() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Agency Address (Street)' ?></th>
                            <td class="col actions"><?= $data->getAgencyStreet() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Agency Address (City)' ?></th>
                            <td class="col actions"><?= $data->getAgencyCity() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Agency Address (State)' ?></th>
                            <td class="col actions"><?= $data->getAgencyState() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Agency Zip Code' ?></th>
                            <td class="col actions"><?= $data->getAgencyZipcode() ?>
                            </td>
                        </tr>

                        <tr>
                            <th scope="col"><?= 'Opportunity Size' ?></th>
                            <td class="col actions"><?= $data->getOpportunitySize() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Opportunity Close ' ?></th>
                            <td class="col actions"><?= $data->getOpportunityCloseDate() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Anticipated Demo Start Date' ?></th>
                            <td class="col actions"><?= $data->getAnticipatedDemoStartDate() ?>
                            </td>
                        </tr>
                        <tr>
                            <th scope="col"><?= 'Tracking No' ?></th>
                            <td class="col actions"><?= $data->getTrackingNo() ?>
                            </td>
                        </tr>

                    </thead>
                </table>
        </div>
        </center>
        <p style="color:red">"convert to Quote" button inactivates the existent quote and creates new one.</p>
        <a class="action primary checkout" href="<?= $block->getUrl('salesforce/index/addquote') . '?mtel_id=' . $data->getTrackingNo() ?>">
            <span><?= $escaper->escapeHtml(__('Convert to Quote')) ?></span>
        </a>
<?php
    } else {
        echo  '<p>No data found or data is already converted to quote.</p>';
    }
} else {
    echo  '<p>No data found!</p>';
}
?>