<?php
/** @var \Mobility\SalesTeamManagement\Block\Customer\SalesRep\AddNew $block */
?>
<form class="form create account form-create-account"
      action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset create account"
              data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field required">
            <label for="email_address" class="label"><span><?= $escaper->escapeHtml(__('Email Address')) ?></span></label>
            <div class="control">
                <input type="email"
                       name="email"
                       autocomplete="email"
                       id="email"
                       title="<?= $escaper->escapeHtmlAttr(__('Email Address')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field required">
            <label for="firstname" class="label"><span><?= $escaper->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="firstname"
                       id="firstname"
                       title="<?= $escaper->escapeHtmlAttr(__('First Name')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="lastname" class="label"><span><?= $escaper->escapeHtml(__('Last Name')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="lastname"
                       id="lastname"
                       title="<?= $escaper->escapeHtmlAttr(__('Last Name')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="ns_internal_id" class="label"><span><?= $escaper->escapeHtml(__('NS Internal Id')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="ns_internal_id"
                       id="ns_internal_id"
                       title="<?= $escaper->escapeHtmlAttr(__('NS Internal Id')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="attu_id" class="label"><span><?= $escaper->escapeHtml(__('Attu Id')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="attu_id"
                       id="attu_id"
                       title="<?= $escaper->escapeHtmlAttr(__('Attu Id')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field required">
            <label for="attu_id" class="label"><span><?= $escaper->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="phone_num"
                       id="phone_num"
                       title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true}">
            </div>
        </div>

        <div class="field required">
        <label for="send_email" class="label"><span><?= $escaper->escapeHtml(__('Send reports via email')) ?></span></label>
            <select name='send_email' class='form-control'>
             <option value="">Send reports via email</option>
             <option value="1" selected='selected'>Yes</option>
             <option value="0">No</option>
            </select>
        </div>

        <div>
            <label for="company_name" class="label"><span><?= $escaper->escapeHtml(__('Company Name')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="company_name"
                       id="company_name"
                       title="<?= $escaper->escapeHtmlAttr(__('Company Name')) ?>"
                       class="input-text"
                       
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action submit primary"
                    title="<?= $escaper->escapeHtmlAttr(__('Create an Account')) ?>">
                <span><?= $escaper->escapeHtml(__('Create an Account')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</form>
