<?php
/** @var \Mobility\SalesTeamManagement\Block\Customer\SalesRep\SalesManagerIndex $block */

$customerCollection = $block->getCustomerCollection(); ?>
<div class="actions-toolbar">
    <a href="<?= $block->escapeUrl($block->getAddNewUrl()) ?>" class="action primary"><?= $block->escapeHtml(__('Add New')) ?></a>
</div>
<?php if ($customerCollection->getSize()): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-salesrep-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Sales Rep')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col firstname"><?= $block->escapeHtml(__('First Name')) ?></th>
                    <th scope="col" class="col lastname"><?= $block->escapeHtml(__('Last Name')) ?></th>
                    <th scope="col" class="col email"><?= $block->escapeHtml(__('Email')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($customerCollection as $customer) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('First Name')) ?>" class="col firstname"><?= $block->escapeHtml($customer->getFirstname()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Last Name')) ?>" class="col lastname"><?= /* @noEscape */ $block->escapeHtml($customer->getLastname()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email"><?= /* @noEscape */ $block->escapeHtml($customer->getEmail()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getEditUrl($customer->getId())) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('Edit')) ?></span>
                            </a>
                            <a href="<?= $block->escapeUrl($block->getDeleteUrl($customer->getId())) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('Delete')) ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__("No record found.")) ?></span></div>
<?php endif ?>

