<?php
$helper  = $this->helper('Magezon\Builder\Helper\Data');
$element = $this->getElement();
$src     = $helper->getImageUrl($element->getData('image'));
$height  = $element->getData('image_height');
$width   = $element->getData('image_width');
$link    = $this->getLinkParams($element->getData('link'));
?>
<?php if ($link['url']) { ?>
<a href="<?= $link['url'] ?>" <?= $link['blank'] ? 'target="_blank"' : '' ?> <?= $link['nofollow'] ? 'rel="nofollow"' : '' ?>>
<?php } ?>
<img src="<?= $src ?>" <?= $width ? 'width="' . $width . '"' : '' ?> <?= $height ? 'height="' . $height . '"' : '' ?>/>
<?php if ($link['url']) { ?>
</a>
<?php } ?>