<?php
/**
 * Bind click to "Add" buttons and bind datepicker to added date fields
 *
 * @var \Magento\Backend\Block\Template $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$scriptString = <<<script
    require(["jquery", "jquery/ui"], function ($) {
        $(function () {
            function bindDatePicker() {
                setTimeout(function() {
                    $(".js-date-excluded-datepicker").datepicker( { dateFormat: "yy/mm/dd" } );
                }, 50);
                $(".js-date-excluded-datepicker").on("cut copy paste contextmenu keydown keypress keyup", function (e) {
                    e.preventDefault();
                });
            }

            bindDatePicker();

            $("button.action-add").on("click", function() {
                bindDatePicker();
            });
        });
    });
script;
?>
<?= isset($secureRenderer)
    ? $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $scriptString, false)
    : '<script>' . $scriptString . '</script>' ?>
