<style>
    * {
        box-sizing: border-box;
    }

    .row {
        margin-left: -5px;
        margin-right: -5px;
    }

    .column {
        float: left;
        width: 50%;
        padding: 5px;
    }

    /* Clearfix (clear floats) */
    .row::after {
        content: "";
        clear: both;
        display: table;
    }

    table {
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        border: 1px solid #ddd;
    }

    th,
    td {
        text-align: left;
        padding: 16px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>
<?php
$demoOrders = $block->getDemoOrderCollection();
$DueBackOrder = $block->getDueBackOrderCollection();
$SaleBySaleRep = $block->getSalesBySalesRepCollection();
$TatalSalesBySalesRep = $block->getTotalSalesBySalesRepCollection();
$OrderInventoryReport = $block->getOrderInventoryReportCollection();
$QuoteRequest = $block->getQuoteRequestCollection();
$ManageSalesRep = $block->getManageSalesRepCollection();
$OrdersApprovals = $block->getOrdersApprovalsCollection();
// echo "<pre>";
// print_r($OrdersApprovals->getData());
// die();
?>
<div class="row">
    <div class="column">
        <div class="row">
            <div class="column">
              <div> 
                 <h3>On Demo Orders</h3>
                
              </div>
            </div>
           
        </div>

        <table>
            <tr>
                <th>SO #</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
            <?php
            foreach ($demoOrders as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('SO #')) ?>" class="col id"><?= $_order->getNsSoNumber() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?= $_order->getCustomerEmail() ?>
                    </td>
                    <td scope="col" class="col action">
                        <a href="<?= $this->getUrl('sales/order/view/order_id/' . $_order->getId()); ?>"><span>
                                <?= $block->escapeHtml(__('View Order')) ?>
                            </span></a>
                            
                    </td>
                </tr>
            <?php endforeach; ?>
            
        </table>
        <a class="column" href="<?= $this->getUrl('customreports/firstnetreports/demoorders') ?>">View All</a>
    </div>
    <div class="column">
        <div class="row">
            <div class="column">
                <h3>Due Back Orders</h3>
               
            </div>
            
        </div>

        <table>
            <tr>
                <th>SO #</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
            <?php foreach ($DueBackOrder as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('SO #')) ?>" class="col id"><?= $_order->getNsSoNumber() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?= $_order->getCustomerEmail() ?>
                    </td>
                    <td scope="col" class="col action">
                        <a href="<?= $this->getUrl('sales/order/view/order_id/' . $_order->getId()); ?>"><span>
                                <?= $block->escapeHtml(__('View Order')) ?>
                            </span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            
        </table>
        <a class="column" href="<?= $this->getUrl('order/index/backorderindex') ?>">View All</a>
    </div>
</div>
<div class="row">
    <div class="column">
        <div class="row">
            <div class="column">
                <h3>Sales By Sales Rep</h3>
                
            </div>
            
        </div>

        <table>
            <tr>
                <th>SO #</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
            <?php foreach ($SaleBySaleRep as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('SO #')) ?>" class="col id"><?= $_order->getNsSoNumber() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?= $_order->getCustomerEmail() ?>
                    </td>
                    <td scope="col" class="col action">
                        <a href="<?= $this->getUrl('sales/order/view/order_id/' . $_order->getId()); ?>"><span>
                                <?= $block->escapeHtml(__('View Order')) ?>
                            </span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            
        </table>
        <a class="column" href="<?= $this->getUrl('customreports/salesmanager/salesreport') ?>">View All</a>
    </div>
    <div class="column">
        <div class="row">
            <div class="column">
                <h3>Total Sales By Sales Rep</h3>
                
            </div>
            
        </div>

        <table>
            <tr>
                
                <th>Email</th>
                <th>Total Orders</th>
                <th>Total Qty</th>
            </tr>
            <?php foreach ($TatalSalesBySalesRep as $_order): ?>
                <tr>
                    
                    <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?= $_order->getEmail() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Total Orders')) ?>" class="col id"><?=  $_order->getTotalOrders() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ number_format($_order->getTotalQty())  ?></td>
                   
                </tr>
            <?php endforeach; ?>
            
        </table>
        <a class="column" href="<?= $this->getUrl('customreports/firstnetreports/totalsales') ?>">View All</a>
    </div>

</div>
<div class="row">
    <div class="column">
        <div class="row">
            <div class="column">
                <h3>Order Inventory Report</h3>
               
            </div>
            
        </div>

        <table>
            <tr>
                <th>Item Name</th>
                <th>Total Orders</th>
                <th>Qty Ordered</th>
            </tr>
            <?php foreach ($OrderInventoryReport as $_order): ?>
                <tr>
                <td data-th="<?= $block->escapeHtml(__('Item Name')) ?>" class="col id"><?php
                if (strlen($_order->getName()) < 30) {
                    echo $_order->getName();
                } else {
                    echo substr($_order->getName(), 0, 30) . '...';
                    }?></td>
                <td data-th="<?= $block->escapeHtml(__('Total Orders')) ?>" class="col id"><?= $_order->getTotalOrders()?></td>
                <td data-th="<?= $block->escapeHtml(__('Qty Ordered')) ?>" class="col total"><?=number_format($_order->getTotalQty())  ?></td>
                </tr>
            <?php endforeach; ?>
            
        </table>
        <a class="column" href="<?= $this->getUrl('customreports/salesmanager/orderinventoryreport') ?>">View All</a>
    </div>
    <div class="column">
        <div class="row">
            <div class="column">
                <h3>Quote Request</h3>
               
            </div>
            
        </div>

        <table>
            <tr>
                <th>Quote #</th>
                <th>Customer Name</th>
                <th>Quote Name</th>
            </tr>
            <?php foreach ($QuoteRequest as $_order): ?>
                <tr>
                <td data-th="<?= $block->escapeHtml(__('Quote #')) ?>" class="col id"><?=$_order->getId() ?></td>
                <td data-th="<?= $block->escapeHtml(__('Customer Name')) ?>" class="col id"><?= $_order->getCustomerName()?></td>
                <td data-th="<?= $block->escapeHtml(__('Quote Name')) ?>" class="col total"><?= $_order->getQuoteName()?></td>
                </tr>
            <?php endforeach; ?>
            
        </table>
        <a class="column" href="<?= $this->getUrl('quote/account/request') ?>">View All</a>
    </div>
</div>
<?php $customertype=$block->getCustomerType();?>
<div class="row">
    <div class="column">
        <div class="row">
            <div class="column">
                <?php if ($customertype == '3') { ?>
                <h3>Sales Rep</h3>
                <?php } elseif($customertype == '4') { ?>
                <h3>Sales Manager</h3>
                <?php } elseif($customertype == '5'){?>
                <h3>Territory Manager</h3>
                <?php } ?>
            </div>
            
        </div>
        <?php if ($customertype == '3'){?>
        <table>
            <tr>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Attu Id</th>
            </tr>
            <?php foreach ($ManageSalesRep as $_order): ?>
                <tr>
                <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?= $_order->getEmail()?></td>
                <td data-th="<?= $block->escapeHtml(__('Phone Number')) ?>" class="col total"><?= $_order->getCustomerPhone()?></td>
                <td data-th="<?= $block->escapeHtml(__('Attu Id')) ?>" class="col id"><?=$_order->getAttuId() ?></td>

                </tr>
            <?php endforeach; ?>
           <?php } else {?>
           <table>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
            </tr>
            <?php foreach ($ManageSalesRep as $_order): ?>
                <tr>
                <td data-th="<?= $block->escapeHtml(__('First Name')) ?>" class="col id"><?= $_order->getFirstname()?></td>
                <td data-th="<?= $block->escapeHtml(__('Last Name')) ?>" class="col total"><?= $_order->getLastname()?></td>
                <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?=$_order->getEmail() ?></td>

                </tr>
            <?php endforeach; ?>
            <?php }?>
        </table><?php if($customertype=='3'){?>
        <a class="column" href="<?= $this->getUrl('customer/salesrep/index') ?>">View All</a>
        <?php } elseif($customertype=='4'){?>
            <a class="column" href="<?= $this->getUrl('customer/salesmanager/index') ?>">View All</a>
            
            <?php }?>

    </div>
    <div class="column">
        <div class="row">
            <div class="column">
                <h3>Orders Approvals</h3>
            </div>
        </div>
        <table>
            <tr>
                <th>Email</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
            <?php foreach ($OrdersApprovals as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col id"><?=$_order->getCustomerEmail() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?php echo  date('m/d/y', strtotime($_order->getCreatedAt()))?></td>
                    <td scope="col" class="col action">
                        <a href="<?= $this->getUrl('sales/order/view/order_id/' . $_order->getId()); ?>">
                        <span>
                            <?= $block->escapeHtml(__('View Order')) ?>
                        </span>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <a class="column" href="<?= $this->getUrl('quote/account/orderapprovals') ?>">View All</a>
    </div>
</div>