<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
    
$numColumns = count($block->getColumns());
  $storeId =  $this->getRequest()->getParam('store');
    
?>
<?php if ($block->getCollection()) : ?>
    <div class="dashboard-item-content">
        <?php if ($block->getCollection()->getSize() > 0) : ?>
            <table class="admin__table-primary dashboard-data" id="<?= $block->escapeHtmlAttr($block->getId()) ?>_table">
                <?php
                /* This part is commented to remove all <col> tags from the code. */
                /* foreach ($block->getColumns() as $_column): ?>
                <col <?= $_column->getHtmlProperty() ?> />
                <?php endforeach; */ ?>
                <?php if ($block->getHeadersVisibility() || $block->getFilterVisibility()) : ?>
                    <thead>
                        <?php if ($block->getHeadersVisibility()) : ?>
                            <tr>
                                <?php foreach ($block->getColumns() as $_column) : ?>
                                    <?= $_column->getHeaderHtml() ?>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif; ?>
                    </thead>
                <?php endif; ?>
                <?php if (!$block->getIsCollapsed()) : ?>
                    <tbody>
                       <?php
                           if($block->getNameInLayout()=='dashboard.lastOrders'){
                           $price=0.00;
                           foreach($block->getCollection() as $order){
                               $url = "https://caad034362.nxcli.net/admin/sales/order/view/order_id/".$order['entity_id'];
                            if($storeId==2){
                                $price='';
                            }else{
                                $price='$'.number_format($order['base_grand_total'], 2);
                            }
                           ?>
                           <tr title="<?php echo $url?> class="even _clickable">
                           <td class=" col-customer "><?php echo $order['customer'];?></td>
                           <td class=" col-items col-number "><?php echo $order['items_count'];?></td>
                           <td class=" col-total a-right last"><?php echo $price;?></td>
                           </tr>
                      <?php
                        }
                          }else if(stripos($block->getNameInLayout(), 'dashboard\tab\products\ordered') !== FALSE){
                            
                            $price=0.00;
                           
                           foreach($block->getCollection() as $order){
                               
                               $url = "https://caad034362.nxcli.net/admin/catalog/product/edit/id/".$order['product_id'];
                            if($storeId==2){
                                $price='';
                            }else{
                                $price='$'.number_format($order['product_price'],2);
                            }
                            ?>
                            <tr title="<?php echo $url?>" class="even _clickable">
                                <td class=" col-customer "><?php echo $order['product_name'];?></td>
                                <td class=" col-items col-number "><?php echo $price;?></td>
                                <td class=" col-total a-right last"><?php echo number_format($order['qty_ordered']);?></td>
                                </tr>
                        
                               <?php
                        }
                        }else if(stripos($block->getNameInLayout(), 'dashboard\tab\customers\newest') !== FALSE){
                            foreach($block->getCollection() as $order){
                                $url = "https://caad034362.nxcli.net/admin/sales/order/view/order_id/".$order['entity_id'];
                                $sumAmount=0.00;
                                $avgAmount=0.00;
                                if($storeId==2){
                                    $sumAmount='';
                                    $avgAmount='';
                                }else{
                                    $sumAmount='$'.number_format($order['orders_sum_amount'],2);
                                    $avgAmount='$'.number_format($order['orders_avg_amount'],2);
                                }
                            ?>
                            <tr title="<?php echo $url?>" class="even _clickable">
                            <td class=" col-name "><?php echo $order['name'];?></td>
                            <td class=" col-orders col-orders_count col-number "><?php echo $order['orders_count'];?></td>
                            <td class=" col-avg col-orders_avg_amount a-right "><?php echo $sumAmount;?></td>
                            <td class=" col-total col-orders_sum_amount a-right last"><?php echo $avgAmount;?></td>
                          </tr>
                            <?php
                                }
                        }else if(stripos($block->getNameInLayout(), 'dashboard\tab\customers\most') !== FALSE){
                            foreach($block->getCollection() as $order){
                                $url = "https://caad034362.nxcli.net/admin/sales/order/view/order_id/".$order['entity_id'];
                                
                                $sumAmount=0.00;
                                $avgAmount=0.00;
                                if($storeId==2){
                                    $sumAmount='';
                                    $avgAmount='';
                                }else{
                                    $sumAmount='$'.number_format($order['orders_sum_amount'],2);
                                    $avgAmount='$'.number_format($order['orders_avg_amount'],2);
                                }
                            ?>
                            <tr title="<?php echo $url?>" class="even _clickable">
                            <td class=" col-name "><?php echo $order['name'];?></td>
                            <td class=" col-orders col-orders_count col-number "><?php echo $order['orders_count'];?></td>
                            <td class=" col-avg col-orders_avg_amount a-right "><?php echo $sumAmount;?></td>
                            <td class=" col-total col-orders_sum_amount a-right last"><?php echo $avgAmount;?></td>
                          </tr>
                            <?php
                                }
                        }else {
                            ?>
                            <?php foreach ($block->getCollection() as $_index => $_item) : ?>
                             <tr title="<?= $block->escapeHtmlAttr($block->getRowUrl($_item)) ?>">
                                        <?php $i = 0;
                                        foreach ($block->getColumns() as $_column) : ?>
                                            <td class="<?= $block->escapeHtmlAttr($_column->getCssProperty()); ?> <?= /* @noEscape */ ++$i == $numColumns ? 'last' : '';
                                                  ?>"><?= /* @noEscape */ (($_html = $_column->getRowField($_item)) != '' ?
                                                      $_html : '&nbsp;') ?></td>
                                              <?php endforeach; ?>
                                          </tr>
                                      <?php endforeach; ?>
                                  <?php
                        }
                       ?>
                    </tbody>
                <?php endif; ?>
            </table>
        <?php else : ?>
            <div class="<?= $block->escapeHtmlAttr($block->getEmptyTextClass());
                        ?>"><?= $block->escapeHtml($block->getEmptyText()) ?></div>
        <?php endif; ?>
    </div>
    <?php if ($block->canDisplayContainer()) : ?>
        <?php $scriptString = 'var deps = [];' . PHP_EOL;
        if ($block->getDependencyJsObject()) {
            $scriptString .= 'deps.push(\'uiRegistry\');' . PHP_EOL;
        }

        if (strpos($block->getRowClickCallback(), 'order.') !== false) {
            $scriptString .= 'deps.push(\'Magento_Sales/order/create/form\');' . PHP_EOL;
        }

        $scriptString .= 'deps.push(\'mage/adminhtml/grid\');' . PHP_EOL;

        $scriptString .= 'require(deps, function(' . ($block->getDependencyJsObject() ? 'registry' : '') . '){' .
            PHP_EOL .
            '//TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed' . PHP_EOL;

        if ($block->getDependencyJsObject()) {
            $scriptString .= 'registry.get(\'' . $block->escapeJs($block->getDependencyJsObject()) .
                '\', function (' . $block->escapeJs($block->getDependencyJsObject()) . ') {' . PHP_EOL;
        }

        $scriptString .= $block->escapeJs($block->getJsObjectName()) . ' = new varienGrid(\'' .
            $block->escapeJs($block->getId()) . '\', \'' . $block->escapeJs($block->getGridUrl()) . '\', \'' .
            $block->escapeJs($block->getVarNamePage()) . '\', \'' .
            $block->escapeJs($block->getVarNameSort()) . '\', \'' .
            $block->escapeJs($block->getVarNameDir()) . '\', \'' .
            $block->escapeJs($block->getVarNameFilter()) . '\');' . PHP_EOL;

        $scriptString .= $block->escapeJs($block->getJsObjectName()) . '.useAjax = \'' .
            $block->escapeJs($block->getUseAjax()) . '\';' . PHP_EOL;
        if ($block->getRowClickCallback()) {
            $scriptString .= $block->escapeJs($block->getJsObjectName()) . '.rowClickCallback = ' .
                /* @noEscape */ $block->getRowClickCallback() . ';' . PHP_EOL;
        }

        if ($block->getCheckboxCheckCallback()) {
            $scriptString .= $block->escapeJs($block->getJsObjectName()) . '.checkboxCheckCallback = ' .
                /* @noEscape */ $block->getCheckboxCheckCallback() . ';' . PHP_EOL;
        }

        if ($block->getRowInitCallback()) {
            $scriptString .= $block->escapeJs($block->getJsObjectName()) . '.initRowCallback = ' .
                /* @noEscape */ $block->getRowInitCallback() . ';' . PHP_EOL;
            $scriptString .= $block->escapeJs($block->getJsObjectName()) . '.rows.each(function(row){' .
                /* @noEscape */ $block->getRowInitCallback() . '(' . $block->escapeJs($block->getJsObjectName()) .
                ', row)});' . PHP_EOL;
        }

        if ($block->getMassactionBlock()->isAvailable()) {
            $scriptString .= /* @noEscape */ $block->getMassactionBlock()->getJavaScript();
        }

        if ($block->getDependencyJsObject()) {
            $scriptString .=  '});' . PHP_EOL;
        }

        $scriptString .= '});' . PHP_EOL;

        echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
        ?>
    <?php endif; ?>
<?php endif ?>

