<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>

<?php 
if($this->getRequest()->getParam('order_id')) {
  $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
  $orderId = $this->getRequest()->getParam('order_id');
  $orderData = $objectManager->create('\Magento\Sales\Model\OrderRepository')->get($orderId);
  $orderInfo = (array)$orderData->getData();
  
  if(isset($orderInfo['usertermstitle'])){
    $paymentTitle = $orderInfo['usertermstitle'];
  }
}
 ?>
<?php 
  //print_r($block->getInfo()->getOrder()->getData());
?>
<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo) : ?>
    <table class="data-table admin__table-secondary">
    <?php foreach ($specificInfo as $label => $value) : ?>
        <tr>
            <th><?= $block->escapeHtml($label) ?>:</th>
            <td>
                <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
