<?php

/** @var \Mobility\CategoryTnCPopup\Block\Popup $block */
if ($block->isLoggedIn() == '1') : ?>
    <div id="cat-tnc-popup">
        <?php
        echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('category-terms-and-condition-popup')
            ->toHtml();
        ?>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function(
                $,
                modal
            ) {
                function setCookie(cname, cvalue, exdays) {
                    var d = new Date();
                    d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
                    var expires = "expires=" + d.toGMTString();
                    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
                }

                function getCookie(cname) {
                    var name = cname + "=";
                    var ca = document.cookie.split(';');
                    for (var i = 0; i < ca.length; i++) {
                        var c = ca[i];
                        while (c.charAt(0) == ' ') {
                            c = c.substring(1);
                        }
                        if (c.indexOf(name) == 0) {
                            return c.substring(name.length, c.length);
                        }
                    }
                    return "";
                }

                function checkCookie(cname) {
                    var user = getCookie(cname);
                    if (user != "") {
                        return "1";
                    } else {
                        return "0";
                    }
                }

                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Ordering',
                    buttons: [{
                            text: $.mage.__('I Agree'),
                            class: '',
                            click: function() {
                                setCookie("category_tnc_popup", 1, 1);
                                this.closeModal();// window.location.href = $('nav.navigation ul li:first-child a').attr('href');
                            }
                        },
                        {
                            text: $.mage.__('I Decline'),
                            class: '',
                            click: function() {
                                this.closeModal();
                            }
                        }
                    ]
                };

                var popup = modal(options, $('#cat-tnc-popup'));
                $(document).ready(function() {
                    var popupShow = checkCookie("category_tnc_popup");
                    if (popupShow != "1") {
                        // e.preventDefault();
                        $('#cat-tnc-popup').modal('openModal');
                    }
                });
                // $('a[href*="/ordering.html"]').click(function(e) {
                //     var popupShow = checkCookie("category_tnc_popup");
                //     if (popupShow != "1") {
                //         e.preventDefault();
                //         $('#cat-tnc-popup').modal('openModal');
                //     }
                // });


            }
        );
    </script>
<?php endif; ?>
