<style>
    @media (min-width: 500px) {
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .optdel {
            display: none !important;
        }

        .row {
            padding-top: 25px;
        }

        .multiselect-dropdown span.maxselected {
            width: 100px;
        }

        .column_total {
            font-weight: bold;

        }

        .column-half {
            float: left;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }

        .button-import {
            white-space: nowrap;
            margin-left: 10px;
        }

        .input-box {
            white-space: nowrap;
            margin-left: 10px;
        }

        .button-pdf {
            white-space: nowrap;
            margin-left: 10px;
        }

        .btn-primary {
            white-space: nowrap;
            margin-left: 10px;
        }

        .search-box {
            position: relative !important;
            line-height: 28px;

        }

        .result {
            position: absolute;
            z-index: 999;
            top: 100%;
            left: -2%;
            background: white;
            width: 103%;
            box-sizing: border-box;
        }

        .result p:hover {
            background-color: lightgrey;
        }
        .scrollit {
    overflow-x:auto;
    white-space: nowrap;
    /* position: relative; */
    /* width: 500px; */
    /* height:500px; */
    /* box-sizing: border-box; */
}

    }
</style>
<form method="GET" action="">
    <div class="row">
        <div class="column-half" style="display: flex; float:right;">

            <button id="export_data" name="export_data" class="button-import" type="submit"> Export Data</button>

        </div>
    </div>

    <?php
    if (isset($_POST['search'])) {
    } else {
        $_location = $block->getLocationDetails();
        // foreach ($_location as $_loc){
        //     print($block->getProductName($_loc->getItemId()));}
        //     die('mateeen');
            echo $block->getChildHtml('info');
            if ($_location && count($_location)) {
            //     foreach ($_location as $_loc){
            //         $r = $block->getProductName($_loc->getItemId());
            //         echo "<pre>";print_r($r);
            // }
            // die("mateeen");
    ?>
            <div class="table-wrapper orders-history">
                <div class="field  required" style="display: flex;float: left;flex-direction: row;justify-content: center;align-items: center;">
                </div>
                <div class="scrollit">
                <table style="overflow-x:auto; " class="data table table-order-items history" id="my-orders-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
                    <thead>
                        <tr>
                            <th scope="col" class="col mcg_sku"><?= $block->escapeHtml(__('MCG SKU')) ?></th>
                            <th scope="col" class="col item_title"><?= $block->escapeHtml(__('Item Title')) ?></th>
                            <th scope="col" class="col location_id"><?= $block->escapeHtml(__('Location Name')) ?></th>
                            <th scope="col" class="col qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                            <th scope="col" class="col action">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($_location as $_loc) : ?>
                            <tr>

                                <?php $product = $block->getProduct($_loc->getItemId());
                                if ($product){
                                    // die('dfgd');
                                    $sku = $product->getName();
                                    $title = $product->getShortDescription();
                                } else {
                                    $sku = '';
                                    $title = '';
                                }
                                ?>
                                <td data-th="<?= $block->escapeHtml(__('MCG SKU')) ?>" class="col mcg_sku"><?= $sku  ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Item Title')) ?>" class="col item_title"><?= substr($title,0,25).'...'?></td>
                                <td data-th="<?= $block->escapeHtml(__('Location Id')) ?>" class="col location_id"><?= substr($_loc->getLocationName(),0,25).'...' ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty"><?= $_loc->getQty() ?></td>
                                <td class="col id"><a href="<?=$block->getUrl().'customreports/mobilecgreports/locationdetail?loc_id='?><?= $_loc->getId() ?>" >View Detail</a></td>
                            </tr>

                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            </div>
            <?php if ($block->getPagerHtml()) : ?>
                <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
            <?php endif ?>
    <?php
        }
    } ?>
     
</form>