<?php
$chartData = $block->orderInventoryReport();
$statusCount = count($chartData);
$demo = $block->onDemo();
$countDemo = count($demo);
$due = $block->due();
$countDue = count($due);
$return = $block->returned();
$countReturn = count($return);

 ?>
<script>
    requirejs(['jquery', 'amcharts'], function($, amcharts) {
        am4core.ready(function() {
            var width = 150;
            // Themes begin
            am4core.useTheme(am4themes_animated);
            // Themes end

            // Create chart instance
            var chart = am4core.create("chartdiv", am4charts.XYChart);
            chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($chartData as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getSku() ?>",
                    value: <?= $ch->getTotalOrders() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);

            });

// Cursor
chart.cursor = new am4charts.XYCursor();


// total qty chart begin
// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("qtychartdiv", am4charts.XYChart);
chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($chartData as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getSku() ?>",
                    value: <?= $ch->getTotalQty() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);
            });

            

            // Cursor
            chart.cursor = new am4charts.XYCursor();
            // total qty chart ends

            // On Demo chart begins
            am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("demochartdiv", am4charts.XYChart);
chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($demo as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getSku() ?>",
                    value: <?= $ch->getOnDemo() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);
            });

            

            // Cursor
            chart.cursor = new am4charts.XYCursor();
            // On Demo chart ends

            // Due orders chart begin
            am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("duechartdiv", am4charts.XYChart);
chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($due as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getSku() ?>",
                    value: <?= $ch->getDue() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);
            });

            

            // Cursor
            chart.cursor = new am4charts.XYCursor();
            // Due orders chart end

            // return orders chart begin
            am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("returnchartdiv", am4charts.XYChart);
chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($return as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getSku() ?>",
                    value: <?= $ch->getReturned() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);
            });

            

            // Cursor
            chart.cursor = new am4charts.XYCursor();
            // return orders chart end

        }); // end am4core.ready()

       

    });
</script>
<!-- orders chart condition -->
<?php if ($statusCount > 0) { ?>
    <style>
        #chartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Order Inventory Orders Chart By Sku</h1>
    <div id="chartdiv"></div>

    
<?php
}
?>
<!-- ordered Qty chart condition -->

<?php if ($statusCount > 0) { ?>
    <style>
        #qtychartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Order Inventory Ordered Qty Chart By Sku</h1>
    <div id="qtychartdiv"></div>

    
<?php
}
?>
<!-- on demo orders chart condition -->

<?php if ($countDemo > 0) { ?>
    <style>
        #demochartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Order Inventory On Demo Orders Chart By Sku</h1>
    <div id="demochartdiv"></div>
    

    
<?php
}
?>
<!-- due orders chart condition -->

<?php if ($countDue > 0) { ?>
    <style>
        #duechartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Order Inventory Due Orders Chart By Sku</h1>
    <div id="duechartdiv"></div>


<?php
}
?>
<!-- return orders chart condition -->

<?php if ($countReturn > 0) { ?>
    <style>
        #returnchartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Order Inventory Returned Orders Chart By Sku</h1>
    <div id="returnchartdiv"></div>

    
<?php
}
?>