<?php
$chartData = $block->salesRepOrders();
$statusCount = count($chartData);
$cartQty=$block->orderdQty();
$qtyCount = count($cartQty);
?>
<script>
    requirejs(['jquery', 'amcharts'], function($, amcharts) {
        am4core.ready(function() {
            var width = 150;
            // Themes begin
            am4core.useTheme(am4themes_animated);
            // Themes end

            // Create chart instance
            var chart = am4core.create("chartdiv", am4charts.XYChart);
            chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($chartData as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getStatus() ?>",
                    value: <?= $ch->getOrders() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);

            });

// Cursor
chart.cursor = new am4charts.XYCursor();


// total qty chart begin
// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("qtychartdiv", am4charts.XYChart);
chart.scrollbarX = new am4core.Scrollbar();

            // Add data
            chart.data = [];

            // Set data
            // var data = [];
            <?php
            foreach ($cartQty as $ch) {
            ?>
                chart.data.push({
                    x_axes: "<?= $ch->getStatus() ?>",
                    value: <?= $ch->getQty() ?>
                });
            <?php
            }
            ?>

            // Create axes
            var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
            categoryAxis.renderer.grid.template.location = 0;
            categoryAxis.dataFields.category = "x_axes";
            categoryAxis.renderer.minGridDistance = 30;
            categoryAxis.fontSize = 11;
            var labelX = categoryAxis.renderer.labels.template;
            labelX.maxWidth = width;
            labelX.truncate = true;
            labelX.wrap = true;
            labelX.tooltipText = "{x_axes}";
            labelX.dy = 5;

            var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
            valueAxis.renderer.minWidth = 50;

            // Create series
            var series = chart.series.push(new am4charts.ColumnSeries());
            series.sequencedInterpolation = true;
            series.dataFields.valueY = "value";
            series.dataFields.categoryX = "x_axes";
            series.tooltipText = "[{categoryX}: bold]{valueY}[/]";
            series.columns.template.strokeWidth = 0;

            series.tooltip.pointerOrientation = "vertical";

            series.columns.template.column.cornerRadiusTopLeft = 10;
            series.columns.template.column.cornerRadiusTopRight = 10;
            series.columns.template.column.fillOpacity = 0.8;

            // on hover, make corner radiuses bigger
            var hoverState = series.columns.template.column.states.create("hover");
            hoverState.properties.cornerRadiusTopLeft = 0;
            hoverState.properties.cornerRadiusTopRight = 0;
            hoverState.properties.fillOpacity = 1;

            series.columns.template.adapter.add("fill", function(fill, target) {
                return chart.colors.getIndex(target.dataItem.index);
            });

            

            // Cursor
            chart.cursor = new am4charts.XYCursor();
        }); // end am4core.ready()

        // start status qty chart

    });
</script>

<?php if ($statusCount > 0) { ?>
    <style>
        #chartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Sales Rep Orders Chart By Status</h1>
    <div id="chartdiv"></div>

    <!-- start status qty chart -->
<?php
}
?>
<?php if ($qtyCount > 0) { ?>
    <style>
        #qtychartdiv {
            width: 100%;
            height: 500px;
        }
    </style>
    <hr>
    <h1>Sales Rep Ordered Qty Chart By Status</h1>
    <div id="qtychartdiv"></div>

    <!-- start status qty chart -->
<?php
}
?>