<?php
$_order = $block->getOrder();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$blockOrderApproval = $objectManager->create('\Mobility\QuoteRequest\Block\Order\OrderApprovalHistory');
?>

<?php if ($_order): ?>
<?php if($blockOrderApproval->getApprovalStatus1($_order->getEntityId()) == 'approved' && $blockOrderApproval->getApprovalStatus2($_order->getEntityId()) == 'approved'){
    
    $resultPageFactory = $objectManager->get('Magento\Framework\View\Result\PageFactory');
    $resultPage = $resultPageFactory->create();
     
    echo $resultPage->getLayout()
    ->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('Cminds_Oapm::email/quote_items.phtml')->setOrder($_order)
    ->toHtml();
    
}else{
   ?>

<?php $_items = $_order->getAllItems(); ?>
<table class="email-items" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #EAEAEA;text-align:left;">
    <thead>
        <tr>
            <th class="item-info" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">
                <?= __('Items') ?>
            </th>
            <th class="item-qty" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">
                <?= __('Qty') ?>
            </th>
            <th class="item-price" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">
                <?= __('Price') ?>
            </th>
        </tr>
    </thead>
    <?php $i = 0; foreach($_items as $_item): ?>
        <?php
            if ($_item->getParentItem()) {
                continue;
            } else $i++;
        ?>
        <tbody<?php echo $i%2 ? ' bgcolor="#F6F6F6"' : '' ?>>
            <?= $block->getItemHtml($_item) ?>
        </tbody>
    <?php endforeach; ?>
    <tfoot class="order-totals">
        <?= $block->getChildHtml('order_totals') ?>
    </tfoot>
</table>
<?php
    
}
?>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
