<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">
              <?php /* @escapeNotVerified */ echo __('Send Order Email') ?>
        </span>
        
    </div>
    <div class="admin__page-section-content">
        <div class="order-information textfied" id="textfiedemailfield">
                <div class="box">
                    <div class="box-content">
                        <p></p>
                    </div>
                </div>
        </div>
    </div>
    <div class="admin__page-section-item-content edit-checkoutfield-date" id="edit-checkoutfield-info-form">      
            <fieldset class="admin__fieldset">
                <input type="hidden" id="orderid" value="<?php 
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();  
                $request = $objectManager->get('Magento\Framework\App\Request\Http');  
                echo $param = $request->getParam('order_id');?>"/>           
                <input type="text" style="height: 30px; min-width:300px" id="emailfield1" class="emailfield1" value="<?php echo $block->getEmailfield1(); ?>">
            </fieldset>
            <br/>
            <button id="emailfield-submit">Send Email</button>
    </div>
</section>
<script type="text/javascript">
    document.querySelector('#emailfield-submit').addEventListener('click', function () {
        document.querySelector('#emailfield-submit').innerHTML = 'Sending...';
        document.querySelector('#emailfield-submit').disabled = true;

        var testEmail = /^[A-Z0-9._%+-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i;
        
        require([
                    'jquery',
                    'mage/validation',
                    'mage/translate',
                    'jquery/ui'
                ], function ($) {
                   
                    
                  //  $("#emailfield-submit").click(function() {
                        var orderid = $('#orderid').val();
                        
                        if($('#emailfield1').length){
                           var emailfield1 = $('#emailfield1').val();
                        }
                        if (testEmail.test(emailfield1)) {
                        
                            var url = '<?= /** @noEscape */ $block->getUrl("customemail/email/sendemail")?>';
                                jQuery.ajax({
                                url: url,
                                data: {orderid: orderid,emailfield1value: emailfield1},
                                type: "POST",
                                async: false,
                            }).done(function (response) {
                            // $("#textfiedemailfield").load(location.href + " #textfiedemailfield");
                                $(".box-content").html("<span style='color:#008000; font-weight:bold'>Email Sent Successfully to " + emailfield1 + "</span>");
                                $("#emailfield-submit").text('Send Email');
                                document.querySelector('#emailfield-submit').disabled = false;
                            });

                        } else {
                            $(".box-content").html("<span style='color:#FF0000'>Please enter valid email address</span>");
                            $("#emailfield-submit").text('Send Email');
                            document.querySelector('#emailfield-submit').disabled = false;
                        }   

                    //});            
                });
    });
                
</script>