<?php
$quote = $block->getFormQuote();
// echo "<pre>";
if ($quote->getData()) {
?>
    <section class="admin__page-section order-view-account-information">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Quote Information')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information">
                <?php /* Quote Information */ ?>

                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tr>
                            <th><?= $block->escapeHtml(__('Quote Id')) ?></th>
                            <td><?= $block->escapeHtml($quote->getId()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Quote Name')) ?></th>
                            <td><?= $block->escapeHtml($quote->getQuoteName()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('ATTUID')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('attuid')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Salesforce Opportunity ID')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('salesforce_opportunity_id')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Length of Demo')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('demo_length')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Name of Agency')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('agency_name')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Discipline')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('discipline')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Opportunity Size')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('opportunity_size')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Opportunity Close Date')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('opportunity_close_date')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Anticipated Demo Start Date')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('anticipated_demo_start_date')) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="admin__page-section-item order-account-information">
                <?php /* quote Information */ ?>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-account-information-table">
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Email Address')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('customer_email')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Phone Number')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('customer_phone')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Contact Name')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('customer_name')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Agency Address (Street)')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('agency_street')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Agency Address (City)')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('agency_city')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Agency Address (State)')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('agency_state')) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Agency Zip Code')) ?></th>
                            <td><?= $block->escapeHtml($quote->getData('agency_zipcode')) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php
} else { ?>
 <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information">
                No Quote found for this order.
            </div>
 </div>
<?php
}
?>