<?php
$_orders = $block->getProduct();

?>
<style>
    @media (min-width: 500px) {

        /* ym */
        .dropdown-content {
            position: absolute;
            background-color: #f6f6f6;
            overflow: auto;
        }

        .dropdown-content a {
            color: black;
            padding: 10px 16px;
            text-decoration: none;
            display: block;
            width: 200px;
        }

        .dropdown-content a:hover {
            background-color: #ddd;
        }

        .show {
            display: block !important;
        }

        .dropdown-values {
            display: none;
        }

        /* ym */
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .optdel {
            display: none !important;
        }

        .row {
            padding-top: 25px;
        }

        .multiselect-dropdown span.maxselected {
            width: 100px;
        }

        .column_total {
            font-weight: bold;

        }

        .column-half {
            float: left;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }

        .button-import {
            white-space: nowrap;
            margin-left: 10px;
        }

        .input-box {
            white-space: nowrap;
            margin-left: 10px;
        }

        .button-pdf {
            white-space: nowrap;
            margin-left: 10px;
        }

        .btn-primary {
            white-space: nowrap;
            margin-left: 10px;
        }

        .search-box {
            position: relative !important;
            line-height: 28px;
        }

        .result {
            position: absolute;
            z-index: 999;
            top: 100%;
            left: 0;
            background: #fff;
            width: 100%;
            box-sizing: border-box;
        }
    }
</style>
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th,
    td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>
<form method="GET" action="">

           <div class="row">
            <div class="column-half" style="width: 70%; display: flex;">
                   <div class="input-box" style="clear: both;">
                   <div class="modelno-repeat">
                   <div class="search-box">
                   <input type="text" name="skus" placeholder="Skus" id="skus" value="<?php if(isset($_GET['skus']) && !empty($_GET['skus'])){
                      echo $_GET['skus'];
                  }else{
                      echo '';
                  }?>"></input>
                   
                 <input type="text" name="customeremail" placeholder="Customer Email"  id="customeremail" value="<?php if(isset($_GET['customeremail']) && !empty($_GET['customeremail'])){
                      echo $_GET['customeremail'];
                  }else{
                      echo '';
                  }?>"></input>
                   
                   </div>
                   </div>
                   </div>
                   <div>
                    <button class="btn btn-primary" name="search" type="submit"><span class="glyphicon glyphicon-search"></span> Search</button>
                </div>
                </div>
           </div>
           <div class="table-wrapper orders-history">
                

                <table class="data table table-order-items history" id="my-orders-table">
                    
                    <thead>
                        <tr>
                            <th scope="col" class="col id"><?= $block->escapeHtml(__('Id #')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('Item Id')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('Item Name')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('Sku')) ?></th>
                            <th scope="col" class="col date"><?= $block->escapeHtml(__('Item Internal Id')) ?></th>
                            <th scope="col" class="col total"><?= $block->escapeHtml(__('Location Id')) ?></th>
                            <th scope="col" class="col status"><?= $block->escapeHtml(__('Qty')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
  
                        foreach ($_orders as $_order) : ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtml(__('Id #')) ?>" class="col id"><?= $_order['id']; ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Item Id')) ?>" class="col date"><?=$_order['item_id'];?></td>
                                <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name"><?=$_order['value'];?></td>
                                <td data-th="<?= $block->escapeHtml(__('Sku')) ?>" class="col sku"><?=$_order['sku'];?></td>
                                <td data-th="<?= $block->escapeHtml(__('Item Internal Id')) ?>" class="col id"><?=$_order['item_internal_id'];?></td>
                                <td data-th="<?= $block->escapeHtml(__('Location Id')) ?>" class="col total"><?=$_order['location_id'];?></td>
                                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col status"><?=$_order['qty'];?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php if ($block->getPagerHtml()) : ?>
                <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
            <?php endif ?>

            </br>
            </br>
            </br>
            <script>
  function addOptions(option) {
    console.log(option);
    let skus = option.join();
    document.getElementById("skus").value = skus;
    console.log(skus);
  }
</script>
</form>