<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$imageUrl = $block->getImageUrl();
$obj = \Magento\Framework\App\ObjectManager::getInstance();
$model = $obj->create('Magento\Catalog\Model\Product');
$product = $model->load($block->getProductId());

foreach ($product->getMediaGalleryImages() as $img) {
    if (isset($img['url']) && $img['url'] != '') {
        $imageUrl = $img['url'];
    }
    break;
}
$width = (int)$block->getWidth();
$paddingBottom = $block->getRatio() * 100;
?>
<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>">
    <span class="product-image-wrapper">
        <img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
         <?php foreach ($block->getCustomAttributes() as $name => $value) : ?>
             <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtml($value) ?>" 
             <?php endforeach; ?> 
             src="<?= $escaper->escapeUrl($imageUrl) ?>
            " loading="lazy" width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>" height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>" alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>" /></span>
</span>
<?php
$styles = <<<STYLE
.product-image-container-{$block->getProductId()} {
    width: {$width}px;
}
.product-image-container-{$block->getProductId()} span.product-image-wrapper {
    padding-bottom: {$paddingBottom}%;
}
STYLE;
//In case a script was using "style" attributes of these elements
$script = <<<SCRIPT
prodImageContainers = document.querySelectorAll(".product-image-container-{$block->getProductId()}");
for (var i = 0; i < prodImageContainers.length; i++) {
    prodImageContainers[i].style.width = "{$width}px";
}
prodImageContainersWrappers = document.querySelectorAll(
    ".product-image-container-{$block->getProductId()}  span.product-image-wrapper"
);
for (var i = 0; i < prodImageContainersWrappers.length; i++) {
    prodImageContainersWrappers[i].style.paddingBottom = "{$paddingBottom}%";
}
SCRIPT;

?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styles, false) ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false) ?>