<?php
/** @var \Mobility\QuoteRequest\Block\Quote\Account\Approval $block */

$quoteRequests = $block->getCustomerQuoteRequestList();

if ($quoteRequests->count()): ?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history">
        <thead>
        <tr>
            <th scope="col" class="col id"><?= $block->escapeHtml(__('Quote #')) ?></th>
            <th scope="col" class="col name"><?= $block->escapeHtml(__('Opportunity')) ?></th>
            <th scope="col" class="col name"><?= $block->escapeHtml(__('Quote Name')) ?></th>
            <th scope="col" class="col status"><?= $block->escapeHtml(__('Approval 1 Status')) ?></th>
            <th scope="col" class="col status"><?= $block->escapeHtml(__('Approval 2 Status')) ?></th>
            <th scope="col" class="col action"><?= $block->escapeHtml(__('Action')) ?></th>
        </tr>
        </thead>
        <tbody>
        	<?php foreach ($quoteRequests as $quoteRequest): ?>
        		<tr>
		            <td scope="col" class="col id"><?= $block->escapeHtml(__('#' . $quoteRequest->getId())) ?></td>
		            <td scope="col" class="col name"><?= $block->escapeHtml($quoteRequest->getOpportunity()) ?></td>
		            <td scope="col" class="col name"><?= $block->escapeHtml($quoteRequest->getQuoteName()) ?></td>
		            <td scope="col" class="col status"><?= $block->escapeHtml(ucfirst($quoteRequest->getApproval1Status())) ?></td>
                    <td scope="col" class="col status"><?= $block->escapeHtml(ucfirst($quoteRequest->getApproval2Status())) ?></td>
                    <td scope="col" class="col action">
                        <?php 
                        if($block->getCustomerType() == 3) {
                            if ($quoteRequest->getApproval1Status() == 'requested') { ?>
                                <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'approved') ?>"><?= $block->escapeHtml(__('Approve')) ?></a> | <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'rejected') ?>"><?= $block->escapeHtml(__('Reject')) ?></a>
                            <?php } else if ($quoteRequest->getApproval1Status() == 'approved') { ?>
                                <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'rejected') ?>"><?= $block->escapeHtml(__('Reject')) ?></a>
                            <?php } else if ($quoteRequest->getApproval1Status() == 'rejected') { ?>
                                <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'approved') ?>"><?= $block->escapeHtml(__('Approve')) ?></a>
                            <?php } else {
                                echo __(" - ");
                            }
                        } else if($block->getCustomerType() == 4) {
                            if ($quoteRequest->getApproval2Status() == 'requested') { ?>
                                <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'approved') ?>"><?= $block->escapeHtml(__('Approve')) ?></a> | <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'rejected') ?>"><?= $block->escapeHtml(__('Reject')) ?></a>
                            <?php } else if ($quoteRequest->getApproval2Status() == 'approved') { ?>
                                <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'rejected') ?>"><?= $block->escapeHtml(__('Reject')) ?></a>
                            <?php } else if ($quoteRequest->getApproval2Status() == 'rejected') { ?>
                                <a href="<?= $block->getStatusAction($quoteRequest->getId(), 'approved') ?>"><?= $block->escapeHtml(__('Approve')) ?></a>
                            <?php } else {
                                echo __(" - ");
                            }
                        } else {
                            echo __(" - ");
                        }
                        ?>
                    </td>
		        </tr>
        	<?php endforeach ?>
        </tbody>
    </table>
</div>
<?php else: ?>
<p><?= __("No record found."); ?></p>
<?php endif; ?>