<style>
    @media (min-width: 500px) {
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .row {
            padding-top: 25px;
        }

        .column-half {
            float: left;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }
    }
</style>
<form method="GET" action="">
    <?php
    /** @var \Mobility\QuoteRequest\Block\Quote\Account\Request $block */
    $quotes = $block->getCustomerQuoteRequestList();
    $quoteRequests = $quotes['quoteCollection'];
    $quoteStatus = $quotes['quoteStatus'];
    ?>
    <div class="row">
        <div class="column-half">
            <input type="date" class="form-control" name="from" required="required" value="<?php if (isset($_GET['from'])) {
                                                                                                echo date('Y-m-d', strtotime($_GET['from']));
                                                                                            } else {
                                                                                                echo date('Y-m-d');
                                                                                            } ?>" />
        </div>
        <div class="column-half">
            <input type="date" class="form-control" name="to" required="required" value="<?php if (isset($_GET['to'])) {
                                                                                                echo date('Y-m-d', strtotime($_GET['to']));
                                                                                            } else {
                                                                                                echo date('Y-m-d');
                                                                                            } ?>" />
        </div>
        <div class="column-half">
            <button class="btn btn-primary" name="search" type="submit"><span class="glyphicon glyphicon-search"></span> Search</button>
        </div>

        <div class="column-half">
            <label class="label" for="Sort By" style="display: block;margin: 0 10px;">
                <span>Quote Status</span>
            </label>
        </div>
        <div class="column-half-right">
            <select name="status" title="Order Status" onchange="location = this.value;">
                <option <?= $quoteStatus == 'all' || $quoteStatus == '' ? 'selected' : ''?> value="<?= $this->getUrl('quote/account/request').'?status=all' ?>">All</option>
                <option <?= $quoteStatus == 'notconverted' ? 'selected' : ''?> value="<?= $this->getUrl('quote/account/request').'?status=notconverted' ?>">Not Converted</option>
                <option <?= $quoteStatus == 'converted' ? 'selected' : ''?> value="<?= $this->getUrl('quote/account/request').'?status=converted' ?>">Converted</option>
            </select>
        </div>
    </div>
    <?php
    if (!empty($quoteRequests)) : ?>

        <div class="table-wrapper orders-history">
            <table class="data table table-order-items history">
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Quote #')) ?></th>
                        <th scope="col" class="col opportunity"><?= $block->escapeHtml(__('Customer Name')) ?></th>
                        <th scope="col" class="col name"><?= $block->escapeHtml(__('Quote Name')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date #')) ?></th>
                        <th scope="col" class="col orderid"><?= $block->escapeHtml(__('Order id')) ?></th>
                        <th scope="col" class="col action"><?= $block->escapeHtml(__('Action')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($quoteRequests as $quoteRequest) : ?>
                        <tr>
                            <td scope="col" class="col id"><?= $block->escapeHtml(__('#' . $quoteRequest->getId())) ?></td>
                            <td scope="col" class="col opportunity"><?= $block->escapeHtml($quoteRequest->getCustomerName()) ?></td>
                            <td scope="col" class="col name"><?= $block->escapeHtml($quoteRequest->getQuoteName()) ?></td>
                            <td scope="col" class="col date"><?= $block->escapeHtml($quoteRequest->getCreatedAt()) ?></td>
                            <td scope="col" class="col orderid"><?= $block->escapeHtml($quoteRequest->getOrderId()) ?></td>
                            <td scope="col" class="col action">
                            <?php if($quoteRequest->getOrderId()==''){
                            ?>
                            <a href="<?= $this->getUrl('quote/status') . 'activate?id=' . $quoteRequest->getId() ?>"><?= $block->escapeHtml('Open') ?></a>
                            <?php
                            }
                            ?></td>
                         </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
    <?php else : ?>
        </br>
        </br>
        <p><?= __("No record found."); ?></p>
    <?php endif; ?>
</form>
