<style>
    @media (min-width: 500px) {
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .column_total {
            font-weight: bold;
            
        }
        
        .row {
            padding-top: 15px;
            padding-bottom: 15px;
        }

        .column-half {
            float: left;
            width: 30%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }

        .button-import {
            white-space: nowrap;
            margin-left: 10px;
        }

        .button-pdf {
            white-space: nowrap;
            margin-left: 10px;
        }
    }
</style>
<?php
  $ordersData = $block->getNewOrderCollection();
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
  $baseUrl = $storeManager->getStore()->getBaseUrl();
?>

<form method="GET" action="">
     <div class="row">
        <div class="column-half" style="display: flex;">

            <button id="export_data" name="export_data" class="button-import" type="submit"> Export Data</button>

        </div>
    </div>
    </form>    
<table class="data table table-order-items history" id="my-orders-table">
      <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
      <thead>
          <tr>

              <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Type')) ?></th>
              <th scope="col" class="col total"><?= $block->escapeHtml(__('Total Orders')) ?></th>
              <th scope="col" class="col total"><?= $block->escapeHtml(__('Total Ordered Quantity')) ?></th>
              <th scope="col" class="col total"></th>

          </tr>
      </thead>
      <tbody>
          <?php 

          foreach ($ordersData as $type => $qtyData) : ?>
              <tr>
                  <td class="col id"><?= ucwords($type) ?></td>
                  <td class="col id"><?= $qtyData['totalOrders'] ?></td>
                  <td class="col id"><?= $qtyData['totalQty'] ?></td>
                  <td class="col id"><a href="<?=$baseUrl?>customreports/mobilecgreports/aereport?otype=<?=$type?>" target="_blank">View Order Portal</a></td>
                  <td class="col id"></td>
              </tr>
          <?php endforeach; ?>
      </tbody>
  </table>
  

  <br/><br/>