<style>
  .switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 34px;
  }

  .switch input {
    opacity: 0;
    width: 0;
    height: 0;
  }

  .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: .4s;
    transition: .4s;
  }

  .slider:before {
    position: absolute;
    content: "";
    height: 26px;
    width: 26px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
  }

  input:checked+.slider {
    background-color: #2196F3;
  }

  input:focus+.slider {
    box-shadow: 0 0 1px #2196F3;
  }

  input:checked+.slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
  }

  /* Rounded sliders */
  .slider.round {
    border-radius: 34px;
  }

  .slider.round:before {
    border-radius: 50%;
  }

  .form-ooo-approval {
    width: 100%;
    display: inline;
  }
</style>
<?php
/** @var \Mobility\OutOfOfficeApprovals\Block\Customer\Account\Approval $block */
$customer = $block->getCustomer();
?>
<form class="form create account form-ooo-approval" action="<?= $escaper->escapeUrl($block->getUrl('oooapprovals/account/approval')) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
  <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
  <fieldset class="fieldset create account" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
  <div class="field">
        	<label for="ooo_enabled" class="label" style="position: relative;top: 7px;margin-right: 10px;"><span><?= $escaper->escapeHtml(__('Out of Office Approval')) ?></span></label>
            <label class="switch">
              <input type="checkbox" name="ooo_enabled" <?= $customer->getCustomAttribute('ooo_enabled') ? $customer->getCustomAttribute('ooo_enabled')->getValue() == 1 ? ' checked=\"checked\"' : '' : '' ?>>
              <span class="slider round"></span>
            </label>
        </div>
        <div class="field">
            <label for="ooo_email" class="label"><span><?= $escaper->escapeHtml(__('Alternate Email Address')) ?></span></label>
            <div class="control">
                <input type="email"
                       name="ooo_email"
                       autocomplete="email"
                       id="email"
                       title="<?= $escaper->escapeHtmlAttr(__('Alternate Email Address')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{'validate-email':true}"
                       value="<?= $customer->getCustomAttribute('ooo_email') ? $customer->getCustomAttribute('ooo_email')->getValue() ? $customer->getCustomAttribute('ooo_email')->getValue() : '' : '' ?>" >
            </div>
        </div>
        <div class="field">
            <label for="ooo_startdate" class="label"><span><?= $escaper->escapeHtml(__('Start Date')) ?></span></label>
            <div class="control">
                <input type="date"
                       name="ooo_startdate"
                       id="start_date"
                       title="<?= $escaper->escapeHtmlAttr(__('Start Date')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       value="<?= $customer->getCustomAttribute('ooo_startdate') ? $customer->getCustomAttribute('ooo_startdate')->getValue() ? date('Y-m-d', strtotime($customer->getCustomAttribute('ooo_startdate')->getValue())) : '' : '' ?>" >

            </div>
        </div>
        <div class="field">
            <label for="ooo_enddate" class="label"><span><?= $escaper->escapeHtml(__('End Date')) ?></span></label>
            <div class="control">
                <input type="date"
                       name="ooo_enddate"
                       id="end_date"
                       title="<?= $escaper->escapeHtmlAttr(__('End Date')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       value="<?= $customer->getCustomAttribute('ooo_enddate') ? $customer->getCustomAttribute('ooo_enddate')->getValue() ? date('Y-m-d', strtotime($customer->getCustomAttribute('ooo_enddate')->getValue())) : '' : '' ?>" >
            </div>
        </div>
  </fieldset>
  <div class="actions-toolbar">
    <div class="primary">
      <button type="submit" class="action submit primary" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>">
        <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
      </button>
    </div>
  </div>
</form>
<script>
  require([
    'jquery',
    'mage/translate',
    'mage/calendar'
  ], function($, $t) {
    $('#start_date', '#end_date').calendar({
      changeMonth: true,
      changeYear: true,
      showButtonPanel: true,
      currentText: $t('Go Today'),
      closeText: $t('Close'),
      showWeek: true,
      showOn: "both"
    });
  })
</script>