<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$currentUrl = $storeManager->getStore()->getCurrentUrl();

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
$orderId='';
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$id = $request->getParam('order_id');
    if(isset($id)){
        $order = $objectManager->create('\Magento\Sales\Model\OrderRepository')->get($id);
        $orderId  = $order->getIncrementId();
    }

    
if (trim($block->getPageHeading())) {
    // if (strpos($currentUrl, 'firstnet/checkout/onepage/success/') !== false) {
    if (0) {
        $titleHtml = '<span class="base" >'
            . "The order has been created and pending approval!"
            .  '</span>';
    } else {
        if($orderId!=''){
            $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
                . $block->getAddBaseAttribute()
                . '>'
            . $block->escapeHtml('Quote #'.$orderId)
                . '</span>';
        }else{
            $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
                . $block->getAddBaseAttribute()
                . '>'
            . $block->escapeHtml($block->getPageHeading())
                . '</span>';
        }
        
    }
}
?>
<?php if ($titleHtml) : ?>
    <div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
        <h1 class="page-title" <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?> <?php if ($block->getAddBaseAttributeAria()) : ?> aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>" <?php endif; ?>>
            <?= /* @noEscape */ $titleHtml ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>

<style>

.price{
    
display:none;
}
</style>
