<?php
$products = $block->getProducts();

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>

<style>
  .flex-container {
    display: flex;
    /* background-color: black; */
  }

  .flex-container .cat-flex-div {
    margin: 10px;
    padding: 20px;
    font-size: 30px;
    width: 50%;
    

  }
  .flex-container {
    display: grid;
  grid-template-columns: repeat(auto-fill,minmax(200px, 1fr));
}
  
</style>

<div class="flex-container">

  <!-- phone category  -->
  <?php foreach($products as $product){ ?>
  <div class="cat-flex-div">
    <div>
      <a href='<?= $product->getProductUrl()?>'>
        <img src="<?= $mediaUrl.'catalog/product/'.$product->getImage() ?>" alt="<?=$product->getName()?>" />
      </a>
    </div>
    <div>
      <a  href='<?= $product->getProductUrl()?>' style='color: black;'><h3><?= $product->getName()?></h3></a>
    </div>
  </div>
<?php } ?>
<div class="cat-flex-div">
    <div>
      <a href='<?=$this->getUrl()?>ordering/show-all.html'>
        <img src="<?= $mediaUrl.'catalog/product/'.$product->getImage() ?>" alt="show-all" />
      </a>
    </div>
    <div>
      <a href='<?=$this->getUrl()?>ordering/show-all.html' style='color: black;'> <h3> Show All </h3></a>
    </div>
  </div>
  </div>

