<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $media = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                        ->getStore()
                        ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    
    $imageSource = $media.'logo/carticon/logo.jpeg';
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $cartUrl = $storeManager->getStore()->getBaseUrl().'checkout/cart/';
/** @var \Magento\Store\Block\Switcher $block */
?>


    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div>
            <div class="action toggle switcher-trigger">
                <a href="<?php echo $cartUrl;?>"><img width="25" height="25" src="<?php echo $imageSource;?>"/></a>
            </div>
            
        </div>
    </div>

