<style>
    @media (min-width: 500px) {
        .row:after {
            content: " ";
            display: table;
            clear: both;
        }

        .row {
            padding-top: 25px;
        }

        .column-half {
            float: left;
            width: 20%;
            padding: 0 5px;
            box-sizing: border-box;
        }

        .column-half-right {
            float: right;
            width: 20%;
            box-sizing: border-box;
        }
    }
</style>
<form method="GET" action="">
    <?php
    /** @var \AscentDigital\SalesForce\Block\Data $block */
    $quotes = $block->getAllSalesForceQuotes();
    $quoteRequests = $quotes['quoteCollection'];
    $quoteStatus = $quotes['quoteStatus'];
    ?>
    <div class="row">
        <div class="column-half">
            <input type="date" class="form-control" name="from" required="required" value="<?php if (isset($_GET['from'])) {
                                                                                                echo date('Y-m-d', strtotime($_GET['from']));
                                                                                            } else {
                                                                                                echo date('Y-m-d');
                                                                                            } ?>" />
        </div>
        <div class="column-half">
            <input type="date" class="form-control" name="to" required="required" value="<?php if (isset($_GET['to'])) {
                                                                                                echo date('Y-m-d', strtotime($_GET['to']));
                                                                                            } else {
                                                                                                echo date('Y-m-d');
                                                                                            } ?>" />
        </div>
        <div class="column-half">
            <button class="btn btn-primary" name="search" type="submit"><span class="glyphicon glyphicon-search"></span> Search</button>
        </div>

        <div class="column-half">
            <label class="label" for="Sort By" style="display: block;margin: 0 10px;">
                <span>Quote Status</span>
            </label>
        </div>
        <div class="column-half-right">
            <select name="status" title="Order Status" onchange="location = this.value;">
                <option <?= $quoteStatus == 'all' || $quoteStatus == '' ? 'selected' : '' ?> value="<?= $this->getUrl('salesforce/salesrep/salesforcequote') . '?status=all' ?>">All</option>
                <option <?= $quoteStatus == 'notconverted' ? 'selected' : '' ?> value="<?= $this->getUrl('salesforce/salesrep/salesforcequote') . '?status=notconverted' ?>">Not Converted</option>
                <option <?= $quoteStatus == 'converted' ? 'selected' : '' ?> value="<?= $this->getUrl('salesforce/salesrep/salesforcequote') . '?status=converted' ?>">Converted</option>
            </select>
        </div>
    </div>
    <?php
    if (!empty($quoteRequests)) : ?>

        <div class="table-wrapper orders-history">
            <table class="data table table-order-items history">
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('S.No')) ?></th>
                        <th scope="col" class="col name"><?= $block->escapeHtml(__('Quote Name')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Date #')) ?></th>
                        <th scope="col" class="col orderid"><?= $block->escapeHtml(__('SFO Id')) ?></th>
                        <th scope="col" class="col orderid"><?= $block->escapeHtml(__('Agency Name')) ?></th>
                        <th scope="col" class="col orderid"><?= $block->escapeHtml(__('Status')) ?></th>
                        <th scope="col" class="col action"><?= $block->escapeHtml(__('Action')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($quoteRequests as $quoteRequest) : ?>
                        <tr>
                            <td scope="col" class="col id"><?= $block->escapeHtml(__('#' . $quoteRequest->getId())) ?></td>
                            <td scope="col" class="col name"><?= $block->escapeHtml($quoteRequest->getQuoteName()) ?></td>
                            <td scope="col" class="col date"><?= $block->escapeHtml($quoteRequest->getCreatedAt()) ?></td>
                            <td scope="col" class="col orderid"><?= $block->escapeHtml($quoteRequest->getSalesforceOpportunityId()) ?></td>
                            <td scope="col" class="col orderid"><?= $block->escapeHtml($quoteRequest->getAgencyName()) ?></td>
                            <td scope="col" class="col orderid"><?= $block->escapeHtml($quoteRequest->getStatus() == 'converted' ? 'converted' : 'not converted') ?></td>
                            <?php if ($quoteRequest->getStatus() != 'converted') { ?>
                                <td scope="col" class="col action"><a href="<?= $this->getUrl('salesforce/index/') . 'addquote?mtel_id=' . $quoteRequest->getTrackingNo() ?>"><?= $block->escapeHtml('Convert') ?></a> | <a href="<?= $this->getUrl('salesforce/index') . 'quotedata?mtel_id=' . $quoteRequest->getTrackingNo() ?>"><?= $block->escapeHtml('View') ?></a></td>
                            <?php } else { ?>
                                <td scope="col" class="col action"></td>
                            <?php } ?>

                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php else : ?>
        </br>
        </br>
        <p><?= __("No record found."); ?></p>
    <?php endif; ?>
</form>