<?php
     $linkedProducts = $block->getCustomLinkedProducts();
     
     if(count($linkedProducts) > 0) {
      echo '<select id="linkedProducts"><option value="#">Select a product</option>';   
      foreach($linkedProducts as $pro) {
          $pid = $pro['linked_product_id'];
          $productData = $block->getLoadProduct($pid);
          $pName = $productData->getName();
          $pUrl = $productData->getProductUrl();
          //echo $pName."<br/>";
          ?>
            <option value="<?=$pUrl?>"><?=$pName?></option>
          <?php
      }
      echo '</select>';
    }
?>

<script>
require(['jquery', 'jquery/ui'], function($){
  $(document).ready( function() {
    $('#linkedProducts').change( function() {
      location.href = $(this).val();
   });
  });
});
</script>