<?php
    $blockPage = $block->getBlockPage();
    $fromDate = $block->getFromDate();
    $toDate = $block->getToDate();
    $orderStatus = $blockPage->getAllOrderStatus();
    $_orders = $blockPage->getFilterOrder($fromDate,$toDate);
?>

<table class="data table table-order-items history" id="my-orders-table">
    <caption class="table-caption"><?= $blockPage->escapeHtml(__('Orders')) ?></caption>
    <thead>
        <tr>
            <th scope="col" class="col id"><?= $blockPage->escapeHtml(__('Order #')) ?></th>
            <th scope="col" class="col date"><?= $blockPage->escapeHtml(__('Date')) ?></th>
            <?= $blockPage->getChildHtml('extra.column.header') ?>
            <th scope="col" class="col total"><?= $blockPage->escapeHtml(__('Order Total')) ?></th>
            <th scope="col" class="col status"><?= $blockPage->escapeHtml(__('Status')) ?></th>
            <th scope="col" class="col actions"><?= $blockPage->escapeHtml(__('Action')) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
            
            foreach ($_orders as $_order) : ?>
            <tr>
                <td data-th="<?= $blockPage->escapeHtml(__('Order #')) ?>" class="col id"><?= $blockPage->escapeHtml($_order->getRealOrderId()) ?></td>
                <td data-th="<?= $blockPage->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $blockPage->formatDate($_order->getCreatedAt()) ?></td>
                <?php $extra = $blockPage->getChildBlock('extra.container'); ?>
                <?php if ($extra) : ?>
                    <?php $extra->setOrder($_order); ?>
                    <?= $extra->getChildHtml() ?>
                <?php endif; ?>
                <td data-th="<?= $blockPage->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                <td data-th="<?= $blockPage->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                <td data-th="<?= $blockPage->escapeHtml(__('Actions')) ?>" class="col actions">
                    <a href="<?= $blockPage->escapeUrl($blockPage->getViewUrl($_order)) ?>" class="action view">
                        <span><?= $blockPage->escapeHtml(__('View Order')) ?></span>
                    </a>
                    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                        <a href="#" data-post='<?= /* @noEscape */
                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                            ->getPostData($blockPage->getReorderUrl($_order))
                        ?>' class="action order">
                            <span><?= $blockPage->escapeHtml(__('Reorder')) ?></span>
                        </a>
                    <?php endif ?>
                </td>
            </tr>
    </tbody>
</table>
